#!/bin/bash

INPUT=$(cat)
FILE_PATH=$(printf '%s' "$INPUT" | grep -o '"file_path"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed -E 's/.*:[[:space:]]*"(.*)"$/\1/')
NORM=$(printf '%s' "$FILE_PATH" | tr '\\' '/')

case "$NORM" in
	*frontend/src/client/generated/* )
		echo "Blocked: '$FILE_PATH' is generated by @hey-api/openapi-ts from backend/src/Api/wwwroot/openapi-v1.json." >&2
		echo "Change the endpoint, Request record, or DTO instead, then run:" >&2
		echo "  dotnet build backend/src/Api/Api.csproj   # refreshes openapi-v1.json" >&2
		echo "  pnpm --dir frontend client:generate                             # refreshes the TypeScript client" >&2
		echo "'pnpm check:client-current' fails CI when the committed output is stale." >&2
		exit 2
		;;
	*backend/tests/IntegrationTests/ApiClient.cs )
		echo "Blocked: '$FILE_PATH' is NSwag-generated (see the '<auto-generated>' header)." >&2
		echo "It regenerates on build via the GenerateApiClient target in backend/tests/IntegrationTests/IntegrationTests.csproj." >&2
		echo "Change the endpoint, Request record, or DTO instead, then run:" >&2
		echo "  dotnet build backend/tests/IntegrationTests/IntegrationTests.csproj" >&2
		exit 2
		;;
	*backend/src/Api/wwwroot/openapi-v1.json )
		echo "Blocked: '$FILE_PATH' is generated from the running API by GenerateOpenApiDocuments." >&2
		echo "Not by NSwag - NSwag only reads this document to generate the C# client." >&2
		echo "Change the endpoint, Request record, or DTO instead, then run:" >&2
		echo "  dotnet build backend/src/Api/Api.csproj" >&2
		exit 2
		;;
esac
exit 0
