#!/bin/bash
# Blocks Edit/Write on NSwag-generated files.
# They regenerate automatically on `dotnet build` (Debug config) via the
# "NSwag" MSBuild target in backend/src/Api/Api.csproj - never hand-edited.

INPUT=$(cat)
FILE_PATH=$(printf '%s' "$INPUT" | grep -o '"file_path"[[:space:]]*:[[:space:]]*"[^"]*"' | head -1 | sed -E 's/.*:[[:space:]]*"(.*)"$/\1/')
NORM=$(printf '%s' "$FILE_PATH" | tr '\\' '/')

case "$NORM" in
	*frontend/src/client/api-client.ts | \
	*backend/tests/IntegrationTests/ApiClient.cs | \
	*backend/src/Api/wwwroot/openapi-v1.json )
		echo "Blocked: '$FILE_PATH' is NSwag-generated (see the '<auto-generated>' header)." >&2
		echo "It regenerates automatically on 'dotnet build' (Debug) via the NSwag MSBuild target in backend/src/Api/Api.csproj." >&2
		echo "Change the endpoint, Request record, or DTO instead, then run:" >&2
		echo "  dotnet build backend/src/Api/Api.csproj --configuration Debug" >&2
		exit 2
		;;
esac
exit 0
