namespace Application.VolunteerOpportunities.GetVolunteerOpportunities.v1;

public sealed record VolunteerOpportunitySummary(
	Guid Id,
	string TitleDe,
	string? TitleEn,
	string? DescriptionDe,
	string? DescriptionEn,
	Guid OrganizationId,
	string OrganizationName,
	string? Street,
	string? HouseNumber,
	string? ZipCode,
	string? City,
	double? Latitude,
	double? Longitude,
	bool IsRemote,
	string Occurrence,
	string ParticipationType,
	string CheckInMethod,
	string? Category,
	IReadOnlyList<string> Tags,
	DateTimeOffset CreatedOn,
	DateTimeOffset? ValidUntil,
	DateTimeOffset? NextTimeSlotStart,
	DateTimeOffset? NextTimeSlotEnd,
	int? TotalMaxParticipants,
	int CurrentParticipantCount,
	string Status,
	string? BannerImageUrl,
	string? OrganizationLogoUrl = null);
