namespace Application.VolunteerOpportunities.GetVolunteerOpportunities.v1;

public sealed record VolunteerOpportunitySummary(
	Guid Id,
	string Title,
	string Description,
	Guid OrganizationId,
	string OrganizationName,
	string? Street,
	string? HouseNumber,
	string? ZipCode,
	string? City,
	double? Latitude,
	double? Longitude,
	bool IsRemote,
	string Occurrence,
	string ParticipationType,
	string CheckInMethod,
	string? Category,
	IReadOnlyList<string> Tags,
	DateTimeOffset CreatedOn,
	int TotalMaxParticipants,
	int CurrentParticipantCount,
	string Status,
	bool HasBannerImage);
