// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DatabaseMigrations.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260329070815_EnhanceBedarfModel")]
    partial class EnhanceBedarfModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Bedarfe.Bedarf", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Frequenz")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("frequenz");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organisation_id");

                    b.Property<DateTimeOffset?>("PublishedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_on");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_bedarfe");

                    b.ToTable("bedarfe", (string)null);
                });

            modelBuilder.Entity("Domain.Organisationen.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<Guid>("KeycloakId")
                        .HasColumnType("uuid")
                        .HasColumnName("keycloak_id");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_organisationen");

                    b.HasIndex("KeycloakId")
                        .IsUnique()
                        .HasDatabaseName("ix_organisationen_keycloak_id");

                    b.ToTable("organisationen", (string)null);
                });

            modelBuilder.Entity("Domain.Bedarfe.Bedarf", b =>
                {
                    b.OwnsOne("Domain.Bedarfe.Adresse", "Adresse", b1 =>
                        {
                            b1.Property<Guid>("BedarfId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Hausnummer")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("adresse_hausnummer");

                            b1.Property<string>("Ort")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("adresse_ort");

                            b1.Property<string>("Plz")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("adresse_plz");

                            b1.Property<string>("Strasse")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("adresse_strasse");

                            b1.HasKey("BedarfId");

                            b1.ToTable("bedarfe");

                            b1.WithOwner()
                                .HasForeignKey("BedarfId")
                                .HasConstraintName("fk_bedarfe_bedarfe_id");
                        });

                    b.Navigation("Adresse")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
