FROM quay.io/keycloak/keycloak:26.5.6 AS builder

ENV KC_DB=postgres
ENV KC_HEALTH_ENABLED=true
ENV KC_METRICS_ENABLED=false

RUN /opt/keycloak/bin/kc.sh build

FROM quay.io/keycloak/keycloak:26.5.6

COPY --from=builder /opt/keycloak/ /opt/keycloak/

HEALTHCHECK NONE

ENTRYPOINT ["/opt/keycloak/bin/kc.sh", "start", "--optimized"]
