// <auto-generated />
using System;
using System.Collections.Generic;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260619062516_AddOrganizationIsVerified")]
    partial class AddOrganizationIsVerified
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Achievements.Achievement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UnlockedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("unlocked_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_achievement");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_achievement_user_id");

                    b.HasIndex("UserId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_achievement_user_id_name");

                    b.ToTable("achievement", (string)null);
                });

            modelBuilder.Entity("Domain.Engagements.Engagement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text")
                        .HasColumnName("cancellation_reason");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsCheckedIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_checked_in");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on");

                    b.Property<Guid>("OpportunityId")
                        .HasColumnType("uuid")
                        .HasColumnName("opportunity_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid?>("TimeSlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("time_slot_id");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid")
                        .HasColumnName("volunteer_id");

                    b.HasKey("Id")
                        .HasName("pk_engagement");

                    b.HasIndex("OpportunityId")
                        .HasDatabaseName("ix_engagement_opportunity_id");

                    b.HasIndex("TimeSlotId")
                        .HasDatabaseName("ix_engagement_time_slot_id");

                    b.HasIndex("VolunteerId")
                        .HasDatabaseName("ix_engagement_volunteer_id");

                    b.HasIndex("OpportunityId", "Status")
                        .HasDatabaseName("ix_engagement_opportunity_id_status");

                    b.HasIndex("VolunteerId", "OpportunityId")
                        .IsUnique()
                        .HasDatabaseName("ix_engagement_volunteer_id_opportunity_id");

                    b.HasIndex("VolunteerId", "Status")
                        .HasDatabaseName("ix_engagement_volunteer_id_status");

                    b.ToTable("engagement", (string)null);
                });

            modelBuilder.Entity("Domain.Notifications.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on");

                    b.Property<Guid>("RecipientId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_id");

                    b.Property<Guid>("RelatedEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_entity_id");

                    b.HasKey("Id")
                        .HasName("pk_notification");

                    b.HasIndex("RecipientId")
                        .HasDatabaseName("ix_notification_recipient_id");

                    b.HasIndex("RecipientId", "CreatedOn")
                        .HasDatabaseName("ix_notification_recipient_id_created_on");

                    b.HasIndex("RecipientId", "IsRead")
                        .HasDatabaseName("ix_notification_recipient_id_is_read");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("Domain.Organizations.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text")
                        .HasColumnName("contact_phone");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_verified");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_organization");

                    b.ToTable("organization", (string)null);
                });

            modelBuilder.Entity("Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("languages");

                    b.Property<string>("PreferredContact")
                        .HasColumnType("text")
                        .HasColumnName("preferred_contact");

                    b.Property<string>("Skills")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("skills");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Domain.Users.UserStreak", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActivityStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("activity_streak");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<int?>("LastActiveIsoWeek")
                        .HasColumnType("integer")
                        .HasColumnName("last_active_iso_week");

                    b.Property<int?>("LastActiveIsoYear")
                        .HasColumnType("integer")
                        .HasColumnName("last_active_iso_year");

                    b.Property<DateOnly?>("LastLoginDate")
                        .HasColumnType("date")
                        .HasColumnName("last_login_date");

                    b.Property<int>("LoginStreak")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("login_streak");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_streak");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_streak_user_id");

                    b.ToTable("user_streak", (string)null);
                });

            modelBuilder.Entity("Domain.VolunteerOpportunities.TimeSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("EndDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date_time");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("integer")
                        .HasColumnName("max_participants");

                    b.Property<DateTimeOffset>("StartDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date_time");

                    b.Property<Guid>("volunteer_opportunity_id")
                        .HasColumnType("uuid")
                        .HasColumnName("volunteer_opportunity_id");

                    b.HasKey("Id")
                        .HasName("pk_time_slot");

                    b.HasIndex("volunteer_opportunity_id")
                        .HasDatabaseName("ix_time_slot_volunteer_opportunity_id");

                    b.ToTable("time_slot", (string)null);
                });

            modelBuilder.Entity("Domain.VolunteerOpportunities.VolunteerOpportunity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BannerImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("banner_image_url");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("CheckInMethod")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("check_in_method");

                    b.Property<string>("CheckInPin")
                        .HasColumnType("text")
                        .HasColumnName("check_in_pin");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_on");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsRemote")
                        .HasColumnType("boolean")
                        .HasColumnName("is_remote");

                    b.Property<DateTimeOffset?>("ModifiedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_on");

                    b.Property<string>("Occurrence")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("occurrence");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("ParticipationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("participation_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.PrimitiveCollection<List<string>>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("tags");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_volunteer_opportunity");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("ix_volunteer_opportunity_organization_id");

                    b.ToTable("volunteer_opportunity", (string)null);
                });

            modelBuilder.Entity("Domain.Engagements.Engagement", b =>
                {
                    b.HasOne("Domain.VolunteerOpportunities.TimeSlot", null)
                        .WithMany()
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_engagement_time_slot_time_slot_id");
                });

            modelBuilder.Entity("Domain.Organizations.Organization", b =>
                {
                    b.OwnsOne("Domain.Common.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("OrganizationId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_city");

                            b1.Property<string>("HouseNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_house_number");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasColumnName("address_zip_code");

                            b1.HasKey("OrganizationId");

                            b1.ToTable("organization");

                            b1.WithOwner()
                                .HasForeignKey("OrganizationId")
                                .HasConstraintName("fk_organization_organization_id");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Domain.VolunteerOpportunities.TimeSlot", b =>
                {
                    b.HasOne("Domain.VolunteerOpportunities.VolunteerOpportunity", null)
                        .WithMany("TimeSlots")
                        .HasForeignKey("volunteer_opportunity_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_time_slot_volunteer_opportunity_volunteer_opportunity_id");
                });

            modelBuilder.Entity("Domain.VolunteerOpportunities.VolunteerOpportunity", b =>
                {
                    b.OwnsOne("Domain.VolunteerOpportunities.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("VolunteerOpportunityId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_city");

                            b1.Property<string>("HouseNumber")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_house_number");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("address_latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("address_longitude");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("address_street");

                            b1.Property<string>("ZipCode")
                                .IsRequired()
                                .HasMaxLength(5)
                                .HasColumnType("character varying(5)")
                                .HasColumnName("address_zip_code");

                            b1.HasKey("VolunteerOpportunityId");

                            b1.ToTable("volunteer_opportunity");

                            b1.WithOwner()
                                .HasForeignKey("VolunteerOpportunityId")
                                .HasConstraintName("fk_volunteer_opportunity_volunteer_opportunity_id");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Domain.VolunteerOpportunities.VolunteerOpportunity", b =>
                {
                    b.Navigation("TimeSlots");
                });
#pragma warning restore 612, 618
        }
    }
}
