// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
	[DbContext(typeof(ApplicationDbContext))]
	[Migration("20260807190000_AddReportTargetDeletedOn")]
	partial class AddReportTargetDeletedOn
	{
		/// <inheritdoc />
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "10.0.10")
				.HasAnnotation("Relational:MaxIdentifierLength", 63);

			NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

			modelBuilder.Entity("Domain.Achievements.Achievement", b =>
				{
					b.Property<Guid>("Id")
						.HasColumnType("uuid")
						.HasColumnName("id");

					b.Property<DateTimeOffset>("CreatedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("created_on");

					b.Property<string>("Description")
						.IsRequired()
						.HasMaxLength(1000)
						.HasColumnType("character varying(1000)")
						.HasColumnName("description");

					b.Property<string>("Key")
						.IsRequired()
						.HasMaxLength(100)
						.HasColumnType("character varying(100)")
						.HasColumnName("key");

					b.Property<DateTimeOffset?>("ModifiedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("modified_on");

					b.Property<string>("Name")
						.IsRequired()
						.HasMaxLength(200)
						.HasColumnType("character varying(200)")
						.HasColumnName("name");

					b.Property<string>("Type")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("type");

					b.Property<DateTimeOffset>("UnlockedAt")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("unlocked_at");

					b.Property<Guid>("UserId")
						.HasColumnType("uuid")
						.HasColumnName("user_id");

					b.HasKey("Id")
						.HasName("pk_achievement");

					b.HasIndex("UserId")
						.HasDatabaseName("ix_achievement_user_id");

					b.HasIndex("UserId", "Key")
						.IsUnique()
						.HasDatabaseName("ix_achievement_user_id_key");

					b.ToTable("achievement", null, t =>
						{
							t.HasCheckConstraint("ck_achievement_type_valid", "type IN ('Milestone', 'Streak', 'Hidden')");
						});
				});

			modelBuilder.Entity("Domain.AuditLogs.AuditLog", b =>
				{
					b.Property<Guid>("Id")
						.HasColumnType("uuid")
						.HasColumnName("id");

					b.Property<string>("ActionType")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("action_type");

					b.Property<Guid>("ActorUserId")
						.HasColumnType("uuid")
						.HasColumnName("actor_user_id");

					b.Property<DateTimeOffset>("CreatedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("created_on");

					b.Property<DateTimeOffset?>("ModifiedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("modified_on");

					b.Property<string>("Reason")
						.HasMaxLength(500)
						.HasColumnType("character varying(500)")
						.HasColumnName("reason");

					b.Property<Guid>("SubjectId")
						.HasColumnType("uuid")
						.HasColumnName("subject_id");

					b.Property<string>("SubjectType")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("subject_type");

					b.HasKey("Id")
						.HasName("pk_audit_log");

					b.HasIndex("CreatedOn")
						.HasDatabaseName("ix_audit_log_created_on");

					b.ToTable("audit_log", null, t =>
						{
							t.HasCheckConstraint("ck_audit_log_action_type_valid", "action_type IN ('UserPromotedToAdmin', 'UserDemotedFromAdmin', 'UserEnabled', 'UserDisabled', 'UserShadowDeleted', 'UserRestored', 'OrganizationShadowDeleted', 'OrganizationRestored', 'VolunteerOpportunityShadowDeleted', 'VolunteerOpportunityRestored', 'EngagementCancelled')");

							t.HasCheckConstraint("ck_audit_log_subject_type_valid", "subject_type IN ('User', 'Organization', 'VolunteerOpportunity', 'Engagement')");
						});
				});

			modelBuilder.Entity("Domain.Engagements.Engagement", b =>
				{
					b.Property<Guid>("Id")
						.HasColumnType("uuid")
						.HasColumnName("id");

					b.Property<string>("CancellationReason")
						.HasColumnType("text")
						.HasColumnName("cancellation_reason");

					b.Property<DateTimeOffset>("CreatedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("created_on");

					b.Property<string>("FeedbackComment")
						.HasMaxLength(500)
						.HasColumnType("character varying(500)")
						.HasColumnName("feedback_comment");

					b.Property<int?>("FeedbackRating")
						.HasColumnType("integer")
						.HasColumnName("feedback_rating");

					b.Property<DateTimeOffset?>("FeedbackSubmittedAt")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("feedback_submitted_at");

					b.Property<bool>("IsCheckedIn")
						.ValueGeneratedOnAdd()
						.HasColumnType("boolean")
						.HasDefaultValue(false)
						.HasColumnName("is_checked_in");

					b.Property<string>("Message")
						.HasColumnType("text")
						.HasColumnName("message");

					b.Property<DateTimeOffset?>("ModifiedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("modified_on");

					b.Property<Guid>("OpportunityId")
						.HasColumnType("uuid")
						.HasColumnName("opportunity_id");

					b.Property<int>("ReactivationCount")
						.ValueGeneratedOnAdd()
						.HasColumnType("integer")
						.HasDefaultValue(0)
						.HasColumnName("reactivation_count");

					b.Property<DateTimeOffset?>("ReminderSentAt")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("reminder_sent_at");

					b.Property<string>("Status")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("status");

					b.Property<DateTimeOffset?>("TimeSlotEndDateTime")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("time_slot_end_date_time");

					b.Property<Guid?>("TimeSlotId")
						.HasColumnType("uuid")
						.HasColumnName("time_slot_id");

					b.Property<DateTimeOffset?>("TimeSlotStartDateTime")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("time_slot_start_date_time");

					b.Property<uint>("Version")
						.IsConcurrencyToken()
						.ValueGeneratedOnAddOrUpdate()
						.HasColumnType("xid")
						.HasColumnName("xmin");

					b.Property<Guid?>("VolunteerId")
						.HasColumnType("uuid")
						.HasColumnName("volunteer_id");

					b.HasKey("Id")
						.HasName("pk_engagement");

					b.HasIndex("OpportunityId")
						.HasDatabaseName("ix_engagement_opportunity_id");

					b.HasIndex("TimeSlotId")
						.HasDatabaseName("ix_engagement_time_slot_id");

					b.HasIndex("VolunteerId")
						.HasDatabaseName("ix_engagement_volunteer_id");

					b.HasIndex("OpportunityId", "Status")
						.HasDatabaseName("ix_engagement_opportunity_id_status");

					b.HasIndex("VolunteerId", "OpportunityId")
						.IsUnique()
						.HasDatabaseName("ix_engagement_volunteer_id_opportunity_id")
						.HasFilter("time_slot_id IS NULL AND status NOT IN ('Cancelled', 'Withdrawn')");

					b.HasIndex("VolunteerId", "Status")
						.HasDatabaseName("ix_engagement_volunteer_id_status");

					b.HasIndex("VolunteerId", "TimeSlotId")
						.IsUnique()
						.HasDatabaseName("ix_engagement_volunteer_id_time_slot_id");

					b.ToTable("engagement", null, t =>
						{
							t.HasCheckConstraint("CK_engagement_feedback_rating_range", "feedback_rating IS NULL OR feedback_rating BETWEEN 1 AND 5");

							t.HasCheckConstraint("ck_engagement_status_valid", "status IN ('Pending', 'Confirmed', 'Cancelled', 'Withdrawn')");
						});
				});

			modelBuilder.Entity("Domain.Notifications.Notification", b =>
				{
					b.Property<Guid>("Id")
						.HasColumnType("uuid")
						.HasColumnName("id");

					b.Property<DateTimeOffset>("CreatedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("created_on");

					b.Property<bool>("IsRead")
						.HasColumnType("boolean")
						.HasColumnName("is_read");

					b.Property<string>("Kind")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("kind");

					b.Property<DateTimeOffset?>("ModifiedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("modified_on");

					b.Property<DateTimeOffset?>("ReadOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("read_on");

					b.Property<Guid>("RecipientId")
						.HasColumnType("uuid")
						.HasColumnName("recipient_id");

					b.Property<Guid>("RelatedEntityId")
						.HasColumnType("uuid")
						.HasColumnName("related_entity_id");

					b.HasKey("Id")
						.HasName("pk_notification");

					b.HasIndex("RecipientId")
						.HasDatabaseName("ix_notification_recipient_id");

					b.HasIndex("IsRead", "CreatedOn")
						.HasDatabaseName("ix_notification_is_read_created_on");

					b.HasIndex("IsRead", "ReadOn")
						.HasDatabaseName("ix_notification_is_read_read_on");

					b.HasIndex("RecipientId", "CreatedOn")
						.HasDatabaseName("ix_notification_recipient_id_created_on");

					b.HasIndex("RecipientId", "IsRead")
						.HasDatabaseName("ix_notification_recipient_id_is_read");

					b.ToTable("notification", null, t =>
						{
							t.HasCheckConstraint("ck_notification_kind_valid", "kind IN ('EngagementCreated', 'EngagementConfirmed', 'EngagementCancelled', 'EngagementWithdrawn', 'OpportunityUpdated', 'OpportunityDeleted', 'OpportunityUnpublished', 'OpportunityCancelled', 'InvitationReceived', 'NewMatchingOpportunity', 'InvitationAccepted', 'InvitationDeclined', 'FeedbackSubmitted')");
						});
				});

			modelBuilder.Entity("Domain.Organizations.Organization", b =>
				{
					b.Property<Guid>("Id")
						.HasColumnType("uuid")
						.HasColumnName("id");

					b.Property<string>("ContactEmail")
						.HasMaxLength(254)
						.HasColumnType("character varying(254)")
						.HasColumnName("contact_email");

					b.Property<string>("ContactPhone")
						.HasMaxLength(30)
						.HasColumnType("character varying(30)")
						.HasColumnName("contact_phone");

					b.Property<DateTimeOffset>("CreatedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("created_on");

					b.Property<DateTimeOffset?>("DeletedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("deleted_on");

					b.Property<string>("Description")
						.HasMaxLength(1000)
						.HasColumnType("character varying(1000)")
						.HasColumnName("description");

					b.Property<bool>("IsDeleted")
						.ValueGeneratedOnAdd()
						.HasColumnType("boolean")
						.HasDefaultValue(false)
						.HasColumnName("is_deleted");

					b.Property<string>("LogoUrl")
						.HasColumnType("text")
						.HasColumnName("logo_url");

					b.Property<DateTimeOffset?>("ModifiedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("modified_on");

					b.Property<string>("Name")
						.IsRequired()
						.HasMaxLength(100)
						.HasColumnType("character varying(100)")
						.HasColumnName("name");

					b.Property<uint>("Version")
						.IsConcurrencyToken()
						.ValueGeneratedOnAddOrUpdate()
						.HasColumnType("xid")
						.HasColumnName("xmin");

					b.Property<string>("Website")
						.HasMaxLength(500)
						.HasColumnType("character varying(500)")
						.HasColumnName("website");

					b.HasKey("Id")
						.HasName("pk_organization");

					b.HasIndex("Name")
						.HasDatabaseName("ix_organization_name");

					b.ToTable("organization", (string)null);
				});

			modelBuilder.Entity("Domain.Organizations.OrganizationDashboardLayout", b =>
				{
					b.Property<Guid>("Id")
						.HasColumnType("uuid")
						.HasColumnName("id");

					b.Property<DateTimeOffset>("CreatedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("created_on");

					b.Property<DateTimeOffset?>("ModifiedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("modified_on");

					b.Property<Guid>("OrganizationId")
						.HasColumnType("uuid")
						.HasColumnName("organization_id");

					b.Property<Guid>("UserId")
						.HasColumnType("uuid")
						.HasColumnName("user_id");

					b.Property<string>("Widgets")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("widgets");

					b.HasKey("Id")
						.HasName("pk_organization_dashboard_layout");

					b.HasIndex("OrganizationId", "UserId")
						.IsUnique()
						.HasDatabaseName("ix_organization_dashboard_layout_organization_id_user_id");

					b.ToTable("organization_dashboard_layout", (string)null);
				});

			modelBuilder.Entity("Domain.Organizations.OrganizationInvitation", b =>
				{
					b.Property<Guid>("Id")
						.HasColumnType("uuid")
						.HasColumnName("id");

					b.Property<DateTimeOffset>("CreatedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("created_on");

					b.Property<DateTimeOffset>("ExpiresOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("expires_on");

					b.Property<string>("IntendedRole")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("intended_role");

					b.Property<Guid>("InvitedById")
						.HasColumnType("uuid")
						.HasColumnName("invited_by_id");

					b.Property<Guid>("InviteeId")
						.HasColumnType("uuid")
						.HasColumnName("invitee_id");

					b.Property<DateTimeOffset?>("ModifiedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("modified_on");

					b.Property<Guid>("OrganizationId")
						.HasColumnType("uuid")
						.HasColumnName("organization_id");

					b.Property<string>("Status")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("status");

					b.Property<uint>("Version")
						.IsConcurrencyToken()
						.ValueGeneratedOnAddOrUpdate()
						.HasColumnType("xid")
						.HasColumnName("xmin");

					b.HasKey("Id")
						.HasName("pk_organization_invitation");

					b.HasIndex("InviteeId")
						.HasDatabaseName("ix_organization_invitation_invitee_id");

					b.HasIndex("OrganizationId")
						.HasDatabaseName("ix_organization_invitation_organization_id");

					b.HasIndex("OrganizationId", "InviteeId")
						.IsUnique()
						.HasDatabaseName("ix_organization_invitation_organization_id_invitee_id")
						.HasFilter("status = 'Pending'");

					b.ToTable("organization_invitation", null, t =>
						{
							t.HasCheckConstraint("ck_organization_invitation_intended_role_valid", "intended_role IN ('Member', 'Organizer')");

							t.HasCheckConstraint("ck_organization_invitation_status_valid", "status IN ('Pending', 'Accepted', 'Declined', 'Expired')");
						});
				});

			modelBuilder.Entity("Domain.Organizations.OrganizationMembership", b =>
				{
					b.Property<Guid>("Id")
						.HasColumnType("uuid")
						.HasColumnName("id");

					b.Property<DateTimeOffset>("CreatedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("created_on");

					b.Property<DateTimeOffset?>("ModifiedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("modified_on");

					b.Property<Guid>("OrganizationId")
						.HasColumnType("uuid")
						.HasColumnName("organization_id");

					b.Property<string>("Role")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("role");

					b.Property<Guid>("UserId")
						.HasColumnType("uuid")
						.HasColumnName("user_id");

					b.HasKey("Id")
						.HasName("pk_organization_membership");

					b.HasIndex("OrganizationId", "UserId")
						.IsUnique()
						.HasDatabaseName("ix_organization_membership_organization_id_user_id");

					b.ToTable("organization_membership", null, t =>
						{
							t.HasCheckConstraint("ck_organization_membership_role_valid", "role IN ('Member', 'Organizer')");
						});
				});

			modelBuilder.Entity("Domain.Reports.Report", b =>
				{
					b.Property<Guid>("Id")
						.HasColumnType("uuid")
						.HasColumnName("id");

					b.Property<DateTimeOffset>("CreatedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("created_on");

					b.Property<string>("Details")
						.HasMaxLength(1000)
						.HasColumnType("character varying(1000)")
						.HasColumnName("details");

					b.Property<DateTimeOffset?>("ModifiedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("modified_on");

					b.Property<string>("Reason")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("reason");

					b.Property<Guid>("ReporterId")
						.HasColumnType("uuid")
						.HasColumnName("reporter_id");

					b.Property<Guid?>("ResolvedByUserId")
						.HasColumnType("uuid")
						.HasColumnName("resolved_by_user_id");

					b.Property<DateTimeOffset?>("ResolvedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("resolved_on");

					b.Property<string>("Status")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("status");

					b.Property<DateTimeOffset?>("TargetDeletedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("target_deleted_on");

					b.Property<Guid>("TargetId")
						.HasColumnType("uuid")
						.HasColumnName("target_id");

					b.Property<string>("TargetType")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("target_type");

					b.HasKey("Id")
						.HasName("pk_report");

					b.HasIndex("Status")
						.HasDatabaseName("ix_report_status");

					b.HasIndex("TargetDeletedOn")
						.HasDatabaseName("ix_report_target_deleted_on");

					b.HasIndex("TargetType", "TargetId")
						.HasDatabaseName("ix_report_target_type_target_id");

					b.ToTable("report", null, t =>
						{
							t.HasCheckConstraint("ck_report_reason_valid", "reason IN ('Spam', 'IllegalContent', 'Fraud', 'Harassment', 'Other')");

							t.HasCheckConstraint("ck_report_status_valid", "status IN ('Open', 'Dismissed', 'Actioned')");

							t.HasCheckConstraint("ck_report_target_type_valid", "target_type IN ('VolunteerOpportunity', 'Organization', 'User')");
						});
				});

			modelBuilder.Entity("Domain.SearchAlerts.SearchAlert", b =>
				{
					b.Property<Guid>("Id")
						.HasColumnType("uuid")
						.HasColumnName("id");

					b.PrimitiveCollection<string[]>("Categories")
						.IsRequired()
						.HasColumnType("text[]")
						.HasColumnName("categories");

					b.Property<double?>("CenterLatitude")
						.HasColumnType("double precision")
						.HasColumnName("center_latitude");

					b.Property<double?>("CenterLongitude")
						.HasColumnType("double precision")
						.HasColumnName("center_longitude");

					b.Property<DateTimeOffset>("CreatedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("created_on");

					b.Property<bool?>("IsRemote")
						.HasColumnType("boolean")
						.HasColumnName("is_remote");

					b.Property<DateTimeOffset>("LastNotifiedAt")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("last_notified_at");

					b.Property<DateTimeOffset?>("ModifiedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("modified_on");

					b.Property<string>("Occurrence")
						.HasColumnType("text")
						.HasColumnName("occurrence");

					b.Property<string>("ParticipationType")
						.HasColumnType("text")
						.HasColumnName("participation_type");

					b.Property<double?>("RadiusKm")
						.HasColumnType("double precision")
						.HasColumnName("radius_km");

					b.Property<string>("Tag")
						.HasColumnType("text")
						.HasColumnName("tag");

					b.Property<Guid>("UserId")
						.HasColumnType("uuid")
						.HasColumnName("user_id");

					b.HasKey("Id")
						.HasName("pk_search_alert");

					b.HasIndex("LastNotifiedAt")
						.HasDatabaseName("ix_search_alert_last_notified_at");

					b.HasIndex("UserId")
						.IsUnique()
						.HasDatabaseName("ix_search_alert_user_id");

					b.ToTable("search_alert", null, t =>
						{
							t.HasCheckConstraint("ck_search_alert_occurrence_valid", "occurrence IS NULL OR occurrence IN ('OneTime', 'Recurring')");

							t.HasCheckConstraint("ck_search_alert_participation_type_valid", "participation_type IS NULL OR participation_type IN ('ScheduledSlots', 'IndividualContact')");
						});
				});

			modelBuilder.Entity("Domain.Users.User", b =>
				{
					b.Property<Guid>("Id")
						.HasColumnType("uuid")
						.HasColumnName("id");

					b.Property<string>("AvatarUrl")
						.HasColumnType("text")
						.HasColumnName("avatar_url");

					b.Property<string>("Bio")
						.HasMaxLength(1000)
						.HasColumnType("character varying(1000)")
						.HasColumnName("bio");

					b.Property<DateTimeOffset>("CreatedOn")
						.ValueGeneratedOnAdd()
						.HasColumnType("timestamp with time zone")
						.HasColumnName("created_on")
						.HasDefaultValueSql("now()");

					b.Property<DateTimeOffset?>("DeletedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("deleted_on");

					b.Property<bool>("IsDeleted")
						.ValueGeneratedOnAdd()
						.HasColumnType("boolean")
						.HasDefaultValue(false)
						.HasColumnName("is_deleted");

					b.Property<string>("Languages")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("languages");

					b.Property<DateTimeOffset?>("ModifiedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("modified_on");

					b.Property<bool>("NotifyOnEngagementCancelled")
						.ValueGeneratedOnAdd()
						.HasColumnType("boolean")
						.HasDefaultValue(true)
						.HasColumnName("notify_on_engagement_cancelled");

					b.Property<bool>("NotifyOnEngagementConfirmed")
						.ValueGeneratedOnAdd()
						.HasColumnType("boolean")
						.HasDefaultValue(true)
						.HasColumnName("notify_on_engagement_confirmed");

					b.Property<bool>("NotifyOnEngagementReminder")
						.ValueGeneratedOnAdd()
						.HasColumnType("boolean")
						.HasDefaultValue(true)
						.HasColumnName("notify_on_engagement_reminder");

					b.Property<bool>("NotifyOnNewSignUp")
						.ValueGeneratedOnAdd()
						.HasColumnType("boolean")
						.HasDefaultValue(true)
						.HasColumnName("notify_on_new_sign_up");

					b.Property<bool>("NotifyOnWithdrawal")
						.ValueGeneratedOnAdd()
						.HasColumnType("boolean")
						.HasDefaultValue(true)
						.HasColumnName("notify_on_withdrawal");

					b.Property<string>("Phone")
						.HasMaxLength(30)
						.HasColumnType("character varying(30)")
						.HasColumnName("phone");

					b.Property<string>("PreferredContact")
						.HasColumnType("text")
						.HasColumnName("preferred_contact");

					b.Property<string>("PreferredLanguage")
						.HasMaxLength(5)
						.HasColumnType("character varying(5)")
						.HasColumnName("preferred_language");

					b.Property<string>("Skills")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("skills");

					b.Property<Guid>("UnsubscribeToken")
						.ValueGeneratedOnAdd()
						.HasColumnType("uuid")
						.HasColumnName("unsubscribe_token")
						.HasDefaultValueSql("gen_random_uuid()");

					b.HasKey("Id")
						.HasName("pk_user");

					b.ToTable("user", null, t =>
						{
							t.HasCheckConstraint("ck_user_preferred_contact_valid", "preferred_contact IN ('Email', 'Phone')");
						});
				});

			modelBuilder.Entity("Domain.Users.UserStreak", b =>
				{
					b.Property<Guid>("Id")
						.HasColumnType("uuid")
						.HasColumnName("id");

					b.Property<int>("ActivityStreak")
						.ValueGeneratedOnAdd()
						.HasColumnType("integer")
						.HasDefaultValue(0)
						.HasColumnName("activity_streak");

					b.Property<DateTimeOffset>("CreatedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("created_on");

					b.Property<int?>("LastActiveIsoWeek")
						.HasColumnType("integer")
						.HasColumnName("last_active_iso_week");

					b.Property<int?>("LastActiveIsoYear")
						.HasColumnType("integer")
						.HasColumnName("last_active_iso_year");

					b.Property<DateOnly?>("LastLoginDate")
						.HasColumnType("date")
						.HasColumnName("last_login_date");

					b.Property<int>("LoginStreak")
						.ValueGeneratedOnAdd()
						.HasColumnType("integer")
						.HasDefaultValue(0)
						.HasColumnName("login_streak");

					b.Property<DateTimeOffset?>("ModifiedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("modified_on");

					b.Property<int>("TotalConfirmedEngagements")
						.ValueGeneratedOnAdd()
						.HasColumnType("integer")
						.HasDefaultValue(0)
						.HasColumnName("total_confirmed_engagements");

					b.Property<Guid>("UserId")
						.HasColumnType("uuid")
						.HasColumnName("user_id");

					b.HasKey("Id")
						.HasName("pk_user_streak");

					b.HasIndex("UserId")
						.IsUnique()
						.HasDatabaseName("ix_user_streak_user_id");

					b.ToTable("user_streak", (string)null);
				});

			modelBuilder.Entity("Domain.VolunteerOpportunities.TimeSlot", b =>
				{
					b.Property<Guid>("Id")
						.HasColumnType("uuid")
						.HasColumnName("id");

					b.Property<DateTimeOffset>("CreatedOn")
						.ValueGeneratedOnAdd()
						.HasColumnType("timestamp with time zone")
						.HasColumnName("created_on")
						.HasDefaultValueSql("now()");

					b.Property<DateTimeOffset>("EndDateTime")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("end_date_time");

					b.Property<int?>("MaxParticipants")
						.HasColumnType("integer")
						.HasColumnName("max_participants");

					b.Property<DateTimeOffset?>("ModifiedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("modified_on");

					b.Property<int?>("RecurrenceCount")
						.HasColumnType("integer")
						.HasColumnName("recurrence_count");

					b.Property<string>("RecurrenceFrequency")
						.HasMaxLength(20)
						.HasColumnType("character varying(20)")
						.HasColumnName("recurrence_frequency");

					b.Property<Guid?>("SeriesId")
						.HasColumnType("uuid")
						.HasColumnName("series_id");

					b.Property<DateTimeOffset>("StartDateTime")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("start_date_time");

					b.Property<Guid>("volunteer_opportunity_id")
						.HasColumnType("uuid")
						.HasColumnName("volunteer_opportunity_id");

					b.HasKey("Id")
						.HasName("pk_time_slot");

					b.HasIndex("EndDateTime")
						.HasDatabaseName("ix_time_slot_end_date_time");

					b.HasIndex("SeriesId")
						.HasDatabaseName("ix_time_slot_series_id");

					b.HasIndex("StartDateTime")
						.HasDatabaseName("ix_time_slot_start_date_time");

					b.HasIndex("volunteer_opportunity_id")
						.HasDatabaseName("ix_time_slot_volunteer_opportunity_id");

					b.ToTable("time_slot", (string)null);
				});

			modelBuilder.Entity("Domain.VolunteerOpportunities.VolunteerOpportunity", b =>
				{
					b.Property<Guid>("Id")
						.HasColumnType("uuid")
						.HasColumnName("id");

					b.Property<bool>("AddressGeocodingFailed")
						.ValueGeneratedOnAdd()
						.HasColumnType("boolean")
						.HasDefaultValue(false)
						.HasColumnName("address_geocoding_failed");

					b.Property<string>("BannerImageUrl")
						.HasColumnType("text")
						.HasColumnName("banner_image_url");

					b.Property<string>("CancellationReason")
						.HasColumnType("text")
						.HasColumnName("cancellation_reason");

					b.Property<string>("Category")
						.HasColumnType("text")
						.HasColumnName("category");

					b.Property<string>("CheckInMethod")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("check_in_method");

					b.Property<string>("CheckInPin")
						.HasColumnType("text")
						.HasColumnName("check_in_pin");

					b.Property<string>("Color")
						.HasColumnType("text")
						.HasColumnName("color");

					b.Property<DateTimeOffset>("CreatedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("created_on");

					b.Property<DateTimeOffset?>("DeletedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("deleted_on");

					b.Property<string>("Description")
						.IsRequired()
						.HasMaxLength(5000)
						.HasColumnType("character varying(5000)")
						.HasColumnName("description");

					b.Property<bool>("IsDeleted")
						.ValueGeneratedOnAdd()
						.HasColumnType("boolean")
						.HasDefaultValue(false)
						.HasColumnName("is_deleted");

					b.Property<bool>("IsRemote")
						.HasColumnType("boolean")
						.HasColumnName("is_remote");

					b.Property<DateTimeOffset?>("ModifiedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("modified_on");

					b.Property<string>("Occurrence")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("occurrence");

					b.Property<Guid>("OrganizationId")
						.HasColumnType("uuid")
						.HasColumnName("organization_id");

					b.Property<string>("ParticipationType")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("participation_type");

					b.Property<DateTimeOffset?>("PublishedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("published_on");

					b.Property<string>("Status")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("status");

					b.PrimitiveCollection<string[]>("Tags")
						.IsRequired()
						.HasColumnType("character varying(50)[]")
						.HasColumnName("tags");

					b.Property<string>("Title")
						.IsRequired()
						.HasMaxLength(200)
						.HasColumnType("character varying(200)")
						.HasColumnName("title");

					b.Property<DateTimeOffset?>("ValidUntil")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("valid_until");

					b.Property<uint>("Version")
						.IsConcurrencyToken()
						.ValueGeneratedOnAddOrUpdate()
						.HasColumnType("xid")
						.HasColumnName("xmin");

					b.HasKey("Id")
						.HasName("pk_volunteer_opportunity");

					b.HasIndex("OrganizationId")
						.HasDatabaseName("ix_volunteer_opportunity_organization_id");

					b.HasIndex("Tags")
						.HasDatabaseName("ix_volunteer_opportunity_tags");

					NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Tags"), "gin");

					b.HasIndex("Status", "CreatedOn")
						.HasDatabaseName("ix_volunteer_opportunity_status_created_on");

					b.HasIndex("Status", "PublishedOn")
						.HasDatabaseName("ix_volunteer_opportunity_status_published_on");

					b.ToTable("volunteer_opportunity", null, t =>
						{
							t.HasCheckConstraint("ck_volunteer_opportunity_category_valid", "category IN ('Social', 'Environment', 'Sport', 'Education', 'DisasterRelief', 'Health', 'Animals', 'Culture', 'Technology', 'Other')");

							t.HasCheckConstraint("ck_volunteer_opportunity_check_in_method_valid", "check_in_method IN ('None', 'QRCode', 'PINCode', 'Manual')");

							t.HasCheckConstraint("ck_volunteer_opportunity_occurrence_valid", "occurrence IN ('OneTime', 'Recurring')");

							t.HasCheckConstraint("ck_volunteer_opportunity_participation_type_valid", "participation_type IN ('ScheduledSlots', 'IndividualContact')");

							t.HasCheckConstraint("ck_volunteer_opportunity_status_valid", "status IN ('Draft', 'Published', 'Unpublished', 'Cancelled')");

							t.HasCheckConstraint("ck_volunteer_opportunity_tags_count", "cardinality(tags) <= 20");
						});
				});

			modelBuilder.Entity("Infrastructure.Persistence.Outbox.OutboxMessage", b =>
				{
					b.Property<Guid>("Id")
						.HasColumnType("uuid")
						.HasColumnName("id");

					b.Property<int>("AttemptCount")
						.ValueGeneratedOnAdd()
						.HasColumnType("integer")
						.HasDefaultValue(0)
						.HasColumnName("attempt_count");

					b.Property<string>("Content")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("content");

					b.Property<string>("Error")
						.HasColumnType("text")
						.HasColumnName("error");

					b.Property<DateTime>("OccurredOnUtc")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("occurred_on_utc");

					b.Property<DateTime?>("ProcessedOnUtc")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("processed_on_utc");

					b.Property<string>("Type")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("type");

					b.HasKey("Id")
						.HasName("pk_outbox_message");

					b.HasIndex("OccurredOnUtc")
						.HasDatabaseName("ix_outbox_message_occurred_on_utc")
						.HasFilter("processed_on_utc IS NULL");

					b.HasIndex("ProcessedOnUtc")
						.HasDatabaseName("ix_outbox_message_processed_on_utc");

					b.ToTable("outbox_message", (string)null);
				});

			modelBuilder.Entity("Infrastructure.Persistence.RateLimiting.CheckInAttempt", b =>
				{
					b.Property<Guid>("EngagementId")
						.HasColumnType("uuid")
						.HasColumnName("engagement_id");

					b.Property<int>("FailedAttempts")
						.HasColumnType("integer")
						.HasColumnName("failed_attempts");

					b.Property<DateTimeOffset>("LastAttemptOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("last_attempt_on");

					b.Property<DateTimeOffset?>("LockedUntil")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("locked_until");

					b.HasKey("EngagementId")
						.HasName("pk_check_in_attempt");

					b.HasIndex("LastAttemptOn")
						.HasDatabaseName("ix_check_in_attempt_last_attempt_on");

					b.ToTable("check_in_attempt", (string)null);
				});

			modelBuilder.Entity("Infrastructure.Persistence.StartupTasks.OrganizationMembershipBackfillState", b =>
				{
					b.Property<int>("Id")
						.HasColumnType("integer")
						.HasColumnName("id");

					b.Property<DateTime>("CompletedOnUtc")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("completed_on_utc");

					b.HasKey("Id")
						.HasName("pk_organization_membership_backfill_state");

					b.ToTable("organization_membership_backfill_state", (string)null);
				});

			modelBuilder.Entity("Domain.Engagements.Engagement", b =>
				{
					b.HasOne("Domain.VolunteerOpportunities.TimeSlot", null)
						.WithMany()
						.HasForeignKey("TimeSlotId")
						.OnDelete(DeleteBehavior.SetNull)
						.HasConstraintName("fk_engagement_time_slot_time_slot_id");
				});

			modelBuilder.Entity("Domain.Organizations.Organization", b =>
				{
					b.OwnsOne("Domain.Common.Address", "Address", b1 =>
						{
							b1.Property<Guid>("OrganizationId")
								.HasColumnType("uuid")
								.HasColumnName("id");

							b1.Property<string>("City")
								.IsRequired()
								.HasMaxLength(100)
								.HasColumnType("character varying(100)")
								.HasColumnName("address_city");

							b1.Property<string>("HouseNumber")
								.IsRequired()
								.HasMaxLength(20)
								.HasColumnType("character varying(20)")
								.HasColumnName("address_house_number");

							b1.Property<string>("Street")
								.IsRequired()
								.HasMaxLength(200)
								.HasColumnType("character varying(200)")
								.HasColumnName("address_street");

							b1.Property<string>("ZipCode")
								.IsRequired()
								.HasMaxLength(5)
								.HasColumnType("character varying(5)")
								.HasColumnName("address_zip_code");

							b1.HasKey("OrganizationId");

							b1.ToTable("organization");

							b1.WithOwner()
								.HasForeignKey("OrganizationId")
								.HasConstraintName("fk_organization_organization_id");
						});

					b.Navigation("Address");
				});

			modelBuilder.Entity("Domain.Organizations.OrganizationDashboardLayout", b =>
				{
					b.HasOne("Domain.Organizations.Organization", null)
						.WithMany()
						.HasForeignKey("OrganizationId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired()
						.HasConstraintName("fk_organization_dashboard_layout_organization_organization_id");
				});

			modelBuilder.Entity("Domain.Organizations.OrganizationInvitation", b =>
				{
					b.HasOne("Domain.Organizations.Organization", null)
						.WithMany()
						.HasForeignKey("OrganizationId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired()
						.HasConstraintName("fk_organization_invitation_organization_organization_id");
				});

			modelBuilder.Entity("Domain.Organizations.OrganizationMembership", b =>
				{
					b.HasOne("Domain.Organizations.Organization", null)
						.WithMany()
						.HasForeignKey("OrganizationId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired()
						.HasConstraintName("fk_organization_membership_organization_organization_id");
				});

			modelBuilder.Entity("Domain.VolunteerOpportunities.TimeSlot", b =>
				{
					b.HasOne("Domain.VolunteerOpportunities.VolunteerOpportunity", null)
						.WithMany("TimeSlots")
						.HasForeignKey("volunteer_opportunity_id")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired()
						.HasConstraintName("fk_time_slot_volunteer_opportunity_volunteer_opportunity_id");
				});

			modelBuilder.Entity("Domain.VolunteerOpportunities.VolunteerOpportunity", b =>
				{
					b.HasOne("Domain.Organizations.Organization", null)
						.WithMany()
						.HasForeignKey("OrganizationId")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired()
						.HasConstraintName("fk_volunteer_opportunity_organization_organization_id");

					b.OwnsOne("Domain.Common.Address", "Address", b1 =>
						{
							b1.Property<Guid>("VolunteerOpportunityId")
								.HasColumnType("uuid")
								.HasColumnName("id");

							b1.Property<string>("City")
								.IsRequired()
								.HasMaxLength(100)
								.HasColumnType("character varying(100)")
								.HasColumnName("address_city");

							b1.Property<string>("HouseNumber")
								.IsRequired()
								.HasMaxLength(20)
								.HasColumnType("character varying(20)")
								.HasColumnName("address_house_number");

							b1.Property<double?>("Latitude")
								.HasColumnType("double precision")
								.HasColumnName("address_latitude");

							b1.Property<double?>("Longitude")
								.HasColumnType("double precision")
								.HasColumnName("address_longitude");

							b1.Property<string>("Street")
								.IsRequired()
								.HasMaxLength(200)
								.HasColumnType("character varying(200)")
								.HasColumnName("address_street");

							b1.Property<string>("ZipCode")
								.IsRequired()
								.HasMaxLength(5)
								.HasColumnType("character varying(5)")
								.HasColumnName("address_zip_code");

							b1.HasKey("VolunteerOpportunityId");

							b1.HasIndex("Latitude", "Longitude")
								.HasDatabaseName("ix_volunteer_opportunity_address_latitude_address_longitude");

							b1.ToTable("volunteer_opportunity");

							b1.WithOwner()
								.HasForeignKey("VolunteerOpportunityId")
								.HasConstraintName("fk_volunteer_opportunity_volunteer_opportunity_id");
						});

					b.Navigation("Address");
				});

			modelBuilder.Entity("Domain.VolunteerOpportunities.VolunteerOpportunity", b =>
				{
					b.Navigation("TimeSlots");
				});
#pragma warning restore 612, 618
		}
	}
}
