// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
	[DbContext(typeof(ApplicationDbContext))]
	partial class ApplicationDbContextModelSnapshot : ModelSnapshot
	{
		protected override void BuildModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
				.HasAnnotation("ProductVersion", "10.0.10")
				.HasAnnotation("Relational:MaxIdentifierLength", 63);

			NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

			modelBuilder.Entity("Domain.Achievements.Achievement", b =>
				{
					b.Property<Guid>("Id")
						.HasColumnType("uuid")
						.HasColumnName("id");

					b.Property<DateTimeOffset>("CreatedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("created_on");

					b.Property<string>("Description")
						.IsRequired()
						.HasMaxLength(1000)
						.HasColumnType("character varying(1000)")
						.HasColumnName("description");

					b.Property<string>("Key")
						.HasMaxLength(100)
						.HasColumnType("character varying(100)")
						.HasColumnName("key");

					b.Property<DateTimeOffset?>("ModifiedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("modified_on");

					b.Property<string>("Name")
						.IsRequired()
						.HasMaxLength(200)
						.HasColumnType("character varying(200)")
						.HasColumnName("name");

					b.Property<string>("Type")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("type");

					b.Property<DateTimeOffset>("UnlockedAt")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("unlocked_at");

					b.Property<Guid>("UserId")
						.HasColumnType("uuid")
						.HasColumnName("user_id");

					b.HasKey("Id")
						.HasName("pk_achievement");

					b.HasIndex("UserId")
						.HasDatabaseName("ix_achievement_user_id");

					b.HasIndex("UserId", "Name")
						.IsUnique()
						.HasDatabaseName("ix_achievement_user_id_name");

					b.ToTable("achievement", (string)null);
				});

			modelBuilder.Entity("Domain.Engagements.Engagement", b =>
				{
					b.Property<Guid>("Id")
						.HasColumnType("uuid")
						.HasColumnName("id");

					b.Property<string>("CancellationReason")
						.HasColumnType("text")
						.HasColumnName("cancellation_reason");

					b.Property<DateTimeOffset>("CreatedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("created_on");

					b.Property<string>("FeedbackComment")
						.HasMaxLength(500)
						.HasColumnType("character varying(500)")
						.HasColumnName("feedback_comment");

					b.Property<int?>("FeedbackRating")
						.HasColumnType("integer")
						.HasColumnName("feedback_rating");

					b.Property<DateTimeOffset?>("FeedbackSubmittedAt")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("feedback_submitted_at");

					b.Property<bool>("IsCheckedIn")
						.ValueGeneratedOnAdd()
						.HasColumnType("boolean")
						.HasDefaultValue(false)
						.HasColumnName("is_checked_in");

					b.Property<string>("Message")
						.HasColumnType("text")
						.HasColumnName("message");

					b.Property<DateTimeOffset?>("ModifiedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("modified_on");

					b.Property<Guid>("OpportunityId")
						.HasColumnType("uuid")
						.HasColumnName("opportunity_id");

					b.Property<DateTimeOffset?>("ReminderSentAt")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("reminder_sent_at");

					b.Property<string>("Status")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("status");

					b.Property<Guid?>("TimeSlotId")
						.HasColumnType("uuid")
						.HasColumnName("time_slot_id");

					b.Property<Guid?>("VolunteerId")
						.HasColumnType("uuid")
						.HasColumnName("volunteer_id");

					b.HasKey("Id")
						.HasName("pk_engagement");

					b.HasIndex("OpportunityId")
						.HasDatabaseName("ix_engagement_opportunity_id");

					b.HasIndex("TimeSlotId")
						.HasDatabaseName("ix_engagement_time_slot_id");

					b.HasIndex("VolunteerId")
						.HasDatabaseName("ix_engagement_volunteer_id");

					b.HasIndex("OpportunityId", "Status")
						.HasDatabaseName("ix_engagement_opportunity_id_status");

					b.HasIndex("VolunteerId", "OpportunityId")
						.IsUnique()
						.HasDatabaseName("ix_engagement_volunteer_id_opportunity_id");

					b.HasIndex("VolunteerId", "Status")
						.HasDatabaseName("ix_engagement_volunteer_id_status");

					b.ToTable("engagement", (string)null);
				});

			modelBuilder.Entity("Domain.Notifications.Notification", b =>
				{
					b.Property<Guid>("Id")
						.HasColumnType("uuid")
						.HasColumnName("id");

					b.Property<DateTimeOffset>("CreatedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("created_on");

					b.Property<bool>("IsRead")
						.HasColumnType("boolean")
						.HasColumnName("is_read");

					b.Property<string>("Kind")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("kind");

					b.Property<DateTimeOffset?>("ModifiedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("modified_on");

					b.Property<Guid>("RecipientId")
						.HasColumnType("uuid")
						.HasColumnName("recipient_id");

					b.Property<Guid>("RelatedEntityId")
						.HasColumnType("uuid")
						.HasColumnName("related_entity_id");

					b.HasKey("Id")
						.HasName("pk_notification");

					b.HasIndex("RecipientId")
						.HasDatabaseName("ix_notification_recipient_id");

					b.HasIndex("RecipientId", "CreatedOn")
						.HasDatabaseName("ix_notification_recipient_id_created_on");

					b.HasIndex("RecipientId", "IsRead")
						.HasDatabaseName("ix_notification_recipient_id_is_read");

					b.ToTable("notification", (string)null);
				});

			modelBuilder.Entity("Domain.Organizations.Organization", b =>
				{
					b.Property<Guid>("Id")
						.HasColumnType("uuid")
						.HasColumnName("id");

					b.Property<string>("ContactEmail")
						.HasColumnType("text")
						.HasColumnName("contact_email");

					b.Property<string>("ContactPhone")
						.HasColumnType("text")
						.HasColumnName("contact_phone");

					b.Property<DateTimeOffset>("CreatedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("created_on");

					b.Property<string>("Description")
						.HasColumnType("text")
						.HasColumnName("description");

					b.Property<bool>("IsVerified")
						.ValueGeneratedOnAdd()
						.HasColumnType("boolean")
						.HasDefaultValue(false)
						.HasColumnName("is_verified");

					b.Property<string>("LogoUrl")
						.HasColumnType("text")
						.HasColumnName("logo_url");

					b.Property<DateTimeOffset?>("ModifiedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("modified_on");

					b.Property<string>("Name")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("name");

					b.Property<string>("Website")
						.HasColumnType("text")
						.HasColumnName("website");

					b.HasKey("Id")
						.HasName("pk_organization");

					b.ToTable("organization", (string)null);
				});

			modelBuilder.Entity("Domain.Organizations.OrganizationDashboardLayout", b =>
				{
					b.Property<Guid>("Id")
						.HasColumnType("uuid")
						.HasColumnName("id");

					b.Property<DateTimeOffset>("CreatedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("created_on");

					b.Property<DateTimeOffset?>("ModifiedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("modified_on");

					b.Property<Guid>("OrganizationId")
						.HasColumnType("uuid")
						.HasColumnName("organization_id");

					b.Property<Guid>("UserId")
						.HasColumnType("uuid")
						.HasColumnName("user_id");

					b.Property<string>("Widgets")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("widgets");

					b.HasKey("Id")
						.HasName("pk_organization_dashboard_layout");

					b.HasIndex("OrganizationId", "UserId")
						.IsUnique()
						.HasDatabaseName("ix_organization_dashboard_layout_organization_id_user_id");

					b.ToTable("organization_dashboard_layout", (string)null);
				});

			modelBuilder.Entity("Domain.Organizations.OrganizationInvitation", b =>
				{
					b.Property<Guid>("Id")
						.HasColumnType("uuid")
						.HasColumnName("id");

					b.Property<DateTimeOffset>("CreatedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("created_on");

					b.Property<Guid>("InvitedById")
						.HasColumnType("uuid")
						.HasColumnName("invited_by_id");

					b.Property<Guid>("InviteeId")
						.HasColumnType("uuid")
						.HasColumnName("invitee_id");

					b.Property<string>("InviteeName")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("invitee_name");

					b.Property<DateTimeOffset?>("ModifiedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("modified_on");

					b.Property<Guid>("OrganizationId")
						.HasColumnType("uuid")
						.HasColumnName("organization_id");

					b.Property<string>("OrganizationName")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("organization_name");

					b.Property<string>("Status")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("status");

					b.HasKey("Id")
						.HasName("pk_organization_invitation");

					b.HasIndex("InviteeId")
						.HasDatabaseName("ix_organization_invitation_invitee_id");

					b.HasIndex("OrganizationId")
						.HasDatabaseName("ix_organization_invitation_organization_id");

					b.ToTable("organization_invitation", (string)null);
				});

			modelBuilder.Entity("Domain.Organizations.OrganizationMembership", b =>
				{
					b.Property<Guid>("Id")
						.HasColumnType("uuid")
						.HasColumnName("id");

					b.Property<DateTimeOffset>("CreatedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("created_on");

					b.Property<DateTimeOffset?>("ModifiedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("modified_on");

					b.Property<Guid>("OrganizationId")
						.HasColumnType("uuid")
						.HasColumnName("organization_id");

					b.Property<string>("Role")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("role");

					b.Property<Guid>("UserId")
						.HasColumnType("uuid")
						.HasColumnName("user_id");

					b.HasKey("Id")
						.HasName("pk_organization_membership");

					b.HasIndex("OrganizationId", "UserId")
						.IsUnique()
						.HasDatabaseName("ix_organization_membership_organization_id_user_id");

					b.ToTable("organization_membership", (string)null);
				});

			modelBuilder.Entity("Domain.Reports.Report", b =>
				{
					b.Property<Guid>("Id")
						.HasColumnType("uuid")
						.HasColumnName("id");

					b.Property<Guid>("ContentId")
						.HasColumnType("uuid")
						.HasColumnName("content_id");

					b.Property<string>("ContentType")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("content_type");

					b.Property<DateTimeOffset>("CreatedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("created_on");

					b.Property<string>("Detail")
						.HasMaxLength(1000)
						.HasColumnType("character varying(1000)")
						.HasColumnName("detail");

					b.Property<DateTimeOffset?>("ModifiedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("modified_on");

					b.Property<string>("Reason")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("reason");

					b.Property<Guid>("ReporterId")
						.HasColumnType("uuid")
						.HasColumnName("reporter_id");

					b.Property<string>("Status")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("status");

					b.HasKey("Id")
						.HasName("pk_report");

					b.HasIndex("Status")
						.HasDatabaseName("ix_report_status");

					b.HasIndex("ContentType", "ContentId")
						.HasDatabaseName("ix_report_content_type_content_id");

					b.ToTable("report", (string)null);
				});

			modelBuilder.Entity("Domain.Users.User", b =>
				{
					b.Property<Guid>("Id")
						.HasColumnType("uuid")
						.HasColumnName("id");

					b.Property<string>("AvatarUrl")
						.HasColumnType("text")
						.HasColumnName("avatar_url");

					b.Property<string>("Bio")
						.HasColumnType("text")
						.HasColumnName("bio");

					b.Property<string>("Languages")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("languages");

					b.Property<string>("PreferredContact")
						.HasColumnType("text")
						.HasColumnName("preferred_contact");

					b.Property<string>("Skills")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("skills");

					b.HasKey("Id")
						.HasName("pk_user");

					b.ToTable("user", (string)null);
				});

			modelBuilder.Entity("Domain.Users.UserStreak", b =>
				{
					b.Property<Guid>("Id")
						.HasColumnType("uuid")
						.HasColumnName("id");

					b.Property<int>("ActivityStreak")
						.ValueGeneratedOnAdd()
						.HasColumnType("integer")
						.HasDefaultValue(0)
						.HasColumnName("activity_streak");

					b.Property<DateTimeOffset>("CreatedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("created_on");

					b.Property<int?>("LastActiveIsoWeek")
						.HasColumnType("integer")
						.HasColumnName("last_active_iso_week");

					b.Property<int?>("LastActiveIsoYear")
						.HasColumnType("integer")
						.HasColumnName("last_active_iso_year");

					b.Property<DateOnly?>("LastLoginDate")
						.HasColumnType("date")
						.HasColumnName("last_login_date");

					b.Property<int>("LoginStreak")
						.ValueGeneratedOnAdd()
						.HasColumnType("integer")
						.HasDefaultValue(0)
						.HasColumnName("login_streak");

					b.Property<DateTimeOffset?>("ModifiedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("modified_on");

					b.Property<int>("TotalConfirmedEngagements")
						.ValueGeneratedOnAdd()
						.HasColumnType("integer")
						.HasDefaultValue(0)
						.HasColumnName("total_confirmed_engagements");

					b.Property<Guid>("UserId")
						.HasColumnType("uuid")
						.HasColumnName("user_id");

					b.HasKey("Id")
						.HasName("pk_user_streak");

					b.HasIndex("UserId")
						.IsUnique()
						.HasDatabaseName("ix_user_streak_user_id");

					b.ToTable("user_streak", (string)null);
				});

			modelBuilder.Entity("Domain.VolunteerOpportunities.TimeSlot", b =>
				{
					b.Property<Guid>("Id")
						.HasColumnType("uuid")
						.HasColumnName("id");

					b.Property<DateTimeOffset>("EndDateTime")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("end_date_time");

					b.Property<int>("MaxParticipants")
						.HasColumnType("integer")
						.HasColumnName("max_participants");

					b.Property<DateTimeOffset>("StartDateTime")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("start_date_time");

					b.Property<Guid>("volunteer_opportunity_id")
						.HasColumnType("uuid")
						.HasColumnName("volunteer_opportunity_id");

					b.HasKey("Id")
						.HasName("pk_time_slot");

					b.HasIndex("volunteer_opportunity_id")
						.HasDatabaseName("ix_time_slot_volunteer_opportunity_id");

					b.ToTable("time_slot", (string)null);
				});

			modelBuilder.Entity("Domain.VolunteerOpportunities.VolunteerOpportunity", b =>
				{
					b.Property<Guid>("Id")
						.HasColumnType("uuid")
						.HasColumnName("id");

					b.Property<string>("BannerImageUrl")
						.HasColumnType("text")
						.HasColumnName("banner_image_url");

					b.Property<string>("Category")
						.HasColumnType("text")
						.HasColumnName("category");

					b.Property<string>("CheckInMethod")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("check_in_method");

					b.Property<string>("CheckInPin")
						.HasColumnType("text")
						.HasColumnName("check_in_pin");

					b.Property<string>("Color")
						.HasColumnType("text")
						.HasColumnName("color");

					b.Property<DateTimeOffset>("CreatedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("created_on");

					b.Property<string>("Description")
						.IsRequired()
						.HasMaxLength(5000)
						.HasColumnType("character varying(5000)")
						.HasColumnName("description");

					b.Property<bool>("IsRemote")
						.HasColumnType("boolean")
						.HasColumnName("is_remote");

					b.Property<DateTimeOffset?>("ModifiedOn")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("modified_on");

					b.Property<string>("Occurrence")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("occurrence");

					b.Property<Guid>("OrganizationId")
						.HasColumnType("uuid")
						.HasColumnName("organization_id");

					b.Property<string>("ParticipationType")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("participation_type");

					b.Property<string>("Status")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("status");

					b.PrimitiveCollection<string[]>("Tags")
						.IsRequired()
						.HasColumnType("text[]")
						.HasColumnName("tags");

					b.Property<string>("Title")
						.IsRequired()
						.HasMaxLength(200)
						.HasColumnType("character varying(200)")
						.HasColumnName("title");

					b.HasKey("Id")
						.HasName("pk_volunteer_opportunity");

					b.HasIndex("OrganizationId")
						.HasDatabaseName("ix_volunteer_opportunity_organization_id");

					b.ToTable("volunteer_opportunity", (string)null);
				});

			modelBuilder.Entity("Infrastructure.Persistence.Outbox.OutboxMessage", b =>
				{
					b.Property<Guid>("Id")
						.HasColumnType("uuid")
						.HasColumnName("id");

					b.Property<string>("Content")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("content");

					b.Property<string>("Error")
						.HasColumnType("text")
						.HasColumnName("error");

					b.Property<DateTime>("OccurredOnUtc")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("occurred_on_utc");

					b.Property<DateTime?>("ProcessedOnUtc")
						.HasColumnType("timestamp with time zone")
						.HasColumnName("processed_on_utc");

					b.Property<string>("Type")
						.IsRequired()
						.HasColumnType("text")
						.HasColumnName("type");

					b.HasKey("Id")
						.HasName("pk_outbox_message");

					b.HasIndex("ProcessedOnUtc")
						.HasDatabaseName("ix_outbox_message_processed_on_utc");

					b.ToTable("outbox_message", (string)null);
				});

			modelBuilder.Entity("Domain.Engagements.Engagement", b =>
				{
					b.HasOne("Domain.VolunteerOpportunities.TimeSlot", null)
						.WithMany()
						.HasForeignKey("TimeSlotId")
						.OnDelete(DeleteBehavior.SetNull)
						.HasConstraintName("fk_engagement_time_slot_time_slot_id");
				});

			modelBuilder.Entity("Domain.Organizations.Organization", b =>
				{
					b.OwnsOne("Domain.Common.Address", "Address", b1 =>
						{
							b1.Property<Guid>("OrganizationId")
								.HasColumnType("uuid")
								.HasColumnName("id");

							b1.Property<string>("City")
								.IsRequired()
								.HasColumnType("text")
								.HasColumnName("address_city");

							b1.Property<string>("HouseNumber")
								.IsRequired()
								.HasColumnType("text")
								.HasColumnName("address_house_number");

							b1.Property<double?>("Latitude")
								.HasColumnType("double precision")
								.HasColumnName("address_latitude");

							b1.Property<double?>("Longitude")
								.HasColumnType("double precision")
								.HasColumnName("address_longitude");

							b1.Property<string>("Street")
								.IsRequired()
								.HasColumnType("text")
								.HasColumnName("address_street");

							b1.Property<string>("ZipCode")
								.IsRequired()
								.HasMaxLength(5)
								.HasColumnType("character varying(5)")
								.HasColumnName("address_zip_code");

							b1.HasKey("OrganizationId");

							b1.ToTable("organization");

							b1.WithOwner()
								.HasForeignKey("OrganizationId")
								.HasConstraintName("fk_organization_organization_id");
						});

					b.Navigation("Address");
				});

			modelBuilder.Entity("Domain.VolunteerOpportunities.TimeSlot", b =>
				{
					b.HasOne("Domain.VolunteerOpportunities.VolunteerOpportunity", null)
						.WithMany("TimeSlots")
						.HasForeignKey("volunteer_opportunity_id")
						.OnDelete(DeleteBehavior.Cascade)
						.IsRequired()
						.HasConstraintName("fk_time_slot_volunteer_opportunity_volunteer_opportunity_id");
				});

			modelBuilder.Entity("Domain.VolunteerOpportunities.VolunteerOpportunity", b =>
				{
					b.OwnsOne("Domain.Common.Address", "Address", b1 =>
						{
							b1.Property<Guid>("VolunteerOpportunityId")
								.HasColumnType("uuid")
								.HasColumnName("id");

							b1.Property<string>("City")
								.IsRequired()
								.HasColumnType("text")
								.HasColumnName("address_city");

							b1.Property<string>("HouseNumber")
								.IsRequired()
								.HasColumnType("text")
								.HasColumnName("address_house_number");

							b1.Property<double?>("Latitude")
								.HasColumnType("double precision")
								.HasColumnName("address_latitude");

							b1.Property<double?>("Longitude")
								.HasColumnType("double precision")
								.HasColumnName("address_longitude");

							b1.Property<string>("Street")
								.IsRequired()
								.HasColumnType("text")
								.HasColumnName("address_street");

							b1.Property<string>("ZipCode")
								.IsRequired()
								.HasMaxLength(5)
								.HasColumnType("character varying(5)")
								.HasColumnName("address_zip_code");

							b1.HasKey("VolunteerOpportunityId");

							b1.ToTable("volunteer_opportunity");

							b1.WithOwner()
								.HasForeignKey("VolunteerOpportunityId")
								.HasConstraintName("fk_volunteer_opportunity_volunteer_opportunity_id");
						});

					b.Navigation("Address");
				});

			modelBuilder.Entity("Domain.VolunteerOpportunities.VolunteerOpportunity", b =>
				{
					b.Navigation("TimeSlots");
				});
#pragma warning restore 612, 618
		}
	}
}
