// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(EinsatzbereitDbContext))]
    [Migration("20260326133608_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Domain.Bedarf", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("EndzeitUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ErstelltAmUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Organisation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("StartzeitUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("bedarfe", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0000-0000-000000000001"),
                            Beschreibung = "Wir brauchen tatkräftige Unterstützung beim Aufbau von Zelten, Ständen und Beschilderung für das jährliche Stadtteil-Sportfest.",
                            EndzeitUtc = new DateTimeOffset(new DateTime(2026, 5, 10, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ErstelltAmUtc = new DateTimeOffset(new DateTime(2026, 3, 20, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Organisation = "TSV Bremen-Nord e.V.",
                            Ort = "Sportplatz Am Bürgerpark, Bremen",
                            StartzeitUtc = new DateTimeOffset(new DateTime(2026, 5, 10, 7, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Titel = "Aufbauhelfer:innen Sportfest"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0000-0000-000000000002"),
                            Beschreibung = "Ehrenamtliche Helfer:innen für die Lebensmittelausgabe gesucht. Einweisung vor Ort, keine Vorkenntnisse nötig.",
                            EndzeitUtc = new DateTimeOffset(new DateTime(2026, 4, 5, 14, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ErstelltAmUtc = new DateTimeOffset(new DateTime(2026, 3, 18, 14, 30, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Organisation = "Bremer Tafel e.V.",
                            Ort = "Bremer Tafel, Findorff",
                            StartzeitUtc = new DateTimeOffset(new DateTime(2026, 4, 5, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Titel = "Essensausgabe Tafel"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0000-0000-000000000003"),
                            Beschreibung = "Wir suchen Freiwillige mit Arabisch- oder Dari-Kenntnissen, die bei der Sozialberatung übersetzen können.",
                            EndzeitUtc = new DateTimeOffset(new DateTime(2026, 4, 12, 16, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ErstelltAmUtc = new DateTimeOffset(new DateTime(2026, 3, 22, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Organisation = "AWO Hamburg e.V.",
                            Ort = "AWO Beratungszentrum, Hamburg-Altona",
                            StartzeitUtc = new DateTimeOffset(new DateTime(2026, 4, 12, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Titel = "Dolmetscher:in für Beratungsstelle"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0001-0000-0000-000000000004"),
                            Beschreibung = "Einmal pro Woche eine Stunde vorlesen oder beim Lesen üben helfen. Flexible Zeiteinteilung möglich.",
                            EndzeitUtc = new DateTimeOffset(new DateTime(2026, 6, 30, 12, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ErstelltAmUtc = new DateTimeOffset(new DateTime(2026, 3, 15, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Organisation = "Mentor Bremen e.V.",
                            Ort = "Grundschule Borgfeld, Bremen",
                            StartzeitUtc = new DateTimeOffset(new DateTime(2026, 4, 7, 8, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Titel = "Lesepat:innen für Grundschule"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
