import { useEffect, useRef } from "react";
import { useTranslation } from "react-i18next";
import { Controller } from "react-hook-form";
import type { Control } from "react-hook-form";
import Dropdown from "../Dropdown";
import TagsInput from "../TagsInput";
import ErrorBanner from "../ErrorBanner";
import { formatDateTime } from "../../lib/format";
import { inputSurfaceClass, labelClass } from "../../lib/formClasses";
import type { OpportunityFormValues } from "./schema";

export type SeriesEditScope = "Only" | "ThisAndFollowing" | "EntireSeries";

interface TimeSlotRow {
	id: string;
	startDateTime: string;
	endDateTime: string;
	maxParticipants: number | null;
	bookedCount: number;
	persisted: boolean;
	/** Set when this occurrence was generated by a recurring create request
	 * (einsatzbereit#1058) - undefined for a standalone slot. */
	seriesId?: string;
	recurrenceFrequency?: string;
	recurrenceCount?: number;
	/** 1-based position of this occurrence within its series, for the badge. */
	seriesPosition?: number;
}

interface EditingSlot {
	id: string;
	startDateTime: string;
	endDateTime: string;
	maxParticipants: number | null;
	scope: SeriesEditScope;
}

interface Props {
	control: Control<OpportunityFormValues>;
	isScheduledSlots: boolean;
	occurrence: string;
	isEditMode: boolean;
	allTimeSlots: TimeSlotRow[];
	removingSlotId: string | null;
	onRemoveExistingSlot: (id: string) => void;
	onRemovePendingSlot: (id: string) => void;
	onRequestRemoveSeriesSlot: (id: string, bookedCount: number) => void;
	editingSlot: EditingSlot | null;
	onStartEditSlot: (slot: TimeSlotRow) => void;
	onEditingSlotChange: (slot: EditingSlot) => void;
	onCancelEditSlot: () => void;
	onSaveEditSlot: (bookedCount: number) => void;
	updatingSlotId: string | null;
	newSlot: {
		startDateTime: string;
		endDateTime: string;
		maxParticipants: number | null;
	};
	onNewSlotChange: (slot: {
		startDateTime: string;
		endDateTime: string;
		maxParticipants: number | null;
	}) => void;
	slotError: string | null;
	addingSlot: boolean;
	onAddSlot: () => void;
	recurrenceFrequency: string;
	onRecurrenceFrequencyChange: (value: string) => void;
	recurrenceCount: number;
	onRecurrenceCountChange: (count: number) => void;
	error: string | null;
	/** Bumped on every submit attempt that sets `error`, including repeats of
	 * the same message - lets the scroll/focus effect below re-run even when
	 * the error text itself didn't change. */
	errorToken: number;
}

const CATEGORY_VALUES = [
	"Social",
	"Environment",
	"Sport",
	"Education",
	"DisasterRelief",
	"Health",
	"Animals",
	"Culture",
	"Technology",
	"Other",
] as const;

export default function DetailsStep({
	control,
	isScheduledSlots,
	occurrence,
	isEditMode,
	allTimeSlots,
	removingSlotId,
	onRemoveExistingSlot,
	onRemovePendingSlot,
	onRequestRemoveSeriesSlot,
	editingSlot,
	onStartEditSlot,
	onEditingSlotChange,
	onCancelEditSlot,
	onSaveEditSlot,
	updatingSlotId,
	newSlot,
	onNewSlotChange,
	slotError,
	addingSlot,
	onAddSlot,
	recurrenceFrequency,
	onRecurrenceFrequencyChange,
	recurrenceCount,
	onRecurrenceCountChange,
	error,
	errorToken,
}: Props) {
	const { t, i18n } = useTranslation();
	const errorRef = useRef<HTMLParagraphElement>(null);

	// Local-timezone "today" as a date-input value, so a deadline can't be
	// picked in the past (mirrors the ScheduledSlots start-time `min` below).
	const today = new Date();
	const todayDateInputValue = new Date(
		today.getTime() - today.getTimezoneOffset() * 60000,
	)
		.toISOString()
		.slice(0, 10);

	// The publish-blocking error (e.g. "needs a time slot") can land below the
	// fold of this step's scrollable body - scroll and focus it into view so
	// it isn't effectively invisible, on top of role="alert" announcing it.
	useEffect(() => {
		if (!error) return;
		errorRef.current?.scrollIntoView({ behavior: "smooth", block: "center" });
		errorRef.current?.focus();
	}, [error, errorToken]);

	return (
		<div className="space-y-5" data-testid="wizard-step-4">
			<div>
				<label htmlFor="create-category" className={`mb-1.5 ${labelClass}`}>
					{t("createOpportunity.fieldCategory")}
				</label>
				<Controller
					name="category"
					control={control}
					render={({ field }) => (
						<Dropdown
							id="create-category"
							value={field.value ?? ""}
							onChange={(v) => field.onChange(v || undefined)}
							className={inputSurfaceClass}
							options={[
								{
									value: "",
									label: t("createOpportunity.fieldCategoryNone"),
								},
								...CATEGORY_VALUES.map((c) => ({
									value: c,
									label: t(`opportunities.category.${c}`),
								})),
							]}
						/>
					)}
				/>
			</div>

			<Controller
				name="tags"
				control={control}
				render={({ field }) => (
					<TagsInput
						id="create-tags"
						label={t("createOpportunity.fieldTags")}
						value={field.value}
						onChange={field.onChange}
						placeholder={t("createOpportunity.fieldTagsPlaceholder")}
						hint={t("createOpportunity.fieldTagsHint")}
					/>
				)}
			/>

			{isScheduledSlots && (
				<div className="rounded-card border border-gray-200 bg-gray-50 p-4">
					<p className="mb-3 text-sm font-semibold text-gray-800">
						{t("timeSlots.sectionTitle")}
					</p>

					{allTimeSlots.length === 0 ? (
						<p className="text-xs text-gray-500">{t("timeSlots.noSlots")}</p>
					) : (
						<ul className="mb-3 space-y-2">
							{allTimeSlots.map((slot) =>
								editingSlot?.id === slot.id ? (
									<li
										key={slot.id}
										className="rounded-lg bg-white px-3 py-2 text-sm shadow-sm"
									>
										<div className="space-y-2">
											{slot.bookedCount > 0 && (
												<p className="text-xs text-amber-600">
													{t("timeSlots.bookedCount", {
														count: slot.bookedCount,
													})}
												</p>
											)}
											{slot.seriesId && (
												<fieldset>
													<legend className="mb-1 text-xs font-medium text-gray-600">
														{t("timeSlots.editScope.legend")}
													</legend>
													<div className="space-y-1">
														{(
															[
																"Only",
																"ThisAndFollowing",
																"EntireSeries",
															] as const
														).map((s) => (
															<label
																key={s}
																className="flex items-center gap-2 text-xs text-gray-700"
															>
																<input
																	type="radio"
																	name={`edit-slot-scope-${slot.id}`}
																	value={s}
																	checked={editingSlot.scope === s}
																	onChange={() =>
																		onEditingSlotChange({
																			...editingSlot,
																			scope: s,
																		})
																	}
																/>
																{t(`timeSlots.editScope.${s}`)}
															</label>
														))}
													</div>
												</fieldset>
											)}
											{editingSlot.scope === "Only" && (
												<div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
													<div>
														<label
															htmlFor={`edit-slot-start-${slot.id}`}
															className="mb-1 block text-xs font-medium text-gray-600"
														>
															{t("timeSlots.fieldStart")}
														</label>
														<input
															id={`edit-slot-start-${slot.id}`}
															type="datetime-local"
															value={editingSlot.startDateTime}
															onChange={(e) =>
																onEditingSlotChange({
																	...editingSlot,
																	startDateTime: e.target.value,
																})
															}
															className={inputSurfaceClass}
														/>
													</div>
													<div>
														<label
															htmlFor={`edit-slot-end-${slot.id}`}
															className="mb-1 block text-xs font-medium text-gray-600"
														>
															{t("timeSlots.fieldEnd")}
														</label>
														<input
															id={`edit-slot-end-${slot.id}`}
															type="datetime-local"
															value={editingSlot.endDateTime}
															onChange={(e) =>
																onEditingSlotChange({
																	...editingSlot,
																	endDateTime: e.target.value,
																})
															}
															className={inputSurfaceClass}
														/>
													</div>
												</div>
											)}
											<div>
												<label
													htmlFor={`edit-slot-max-${slot.id}`}
													className="mb-1 block text-xs font-medium text-gray-600"
												>
													{t("timeSlots.fieldMaxParticipants")}
												</label>
												<div className="flex items-center gap-3">
													<input
														id={`edit-slot-max-${slot.id}`}
														type="number"
														min={1}
														disabled={editingSlot.maxParticipants === null}
														value={editingSlot.maxParticipants ?? ""}
														onChange={(e) =>
															onEditingSlotChange({
																...editingSlot,
																maxParticipants:
																	parseInt(e.target.value, 10) || 1,
															})
														}
														className="w-24 rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm shadow-sm transition focus:border-brand-400 disabled:bg-gray-100 disabled:text-gray-400"
													/>
													<label
														htmlFor={`edit-slot-unlimited-${slot.id}`}
														className="flex items-center gap-1.5 text-xs font-medium text-gray-600"
													>
														<input
															id={`edit-slot-unlimited-${slot.id}`}
															type="checkbox"
															checked={editingSlot.maxParticipants === null}
															onChange={(e) =>
																onEditingSlotChange({
																	...editingSlot,
																	maxParticipants: e.target.checked ? null : 1,
																})
															}
															className="h-3.5 w-3.5 rounded border-gray-300 text-brand-600"
														/>
														{t("timeSlots.unlimited")}
													</label>
												</div>
											</div>
											<div className="flex justify-end gap-3">
												<button
													type="button"
													onClick={onCancelEditSlot}
													className="text-xs text-gray-500 hover:underline"
												>
													{t("timeSlots.cancelEditButton")}
												</button>
												<button
													type="button"
													disabled={updatingSlotId === slot.id}
													onClick={() => onSaveEditSlot(slot.bookedCount)}
													className="rounded-lg border border-brand-200 bg-white px-3 py-1.5 text-xs font-semibold text-brand-700 transition hover:bg-brand-50 disabled:opacity-50"
												>
													{updatingSlotId === slot.id
														? t("timeSlots.editing")
														: t("timeSlots.saveButton")}
												</button>
											</div>
										</div>
									</li>
								) : (
									<li
										key={slot.id}
										className="flex items-center justify-between rounded-lg bg-white px-3 py-2 text-sm shadow-sm"
									>
										<span className="text-gray-700">
											{formatDateTime(slot.startDateTime, i18n.language)} -{" "}
											{formatDateTime(slot.endDateTime, i18n.language)} (
											{slot.maxParticipants === null
												? t("timeSlots.unlimited")
												: slot.maxParticipants}
											)
											{slot.seriesId && slot.recurrenceCount && (
												<span className="ml-2 rounded-full bg-brand-50 px-2 py-0.5 text-xs text-brand-700">
													{t("timeSlots.seriesBadge", {
														frequency: t(
															`timeSlots.recurrence${slot.recurrenceFrequency}`,
														),
														position: slot.seriesPosition,
														count: slot.recurrenceCount,
													})}
												</span>
											)}
											{slot.bookedCount > 0 && (
												<span className="ml-2 text-xs text-gray-500">
													{t("timeSlots.bookedCount", {
														count: slot.bookedCount,
													})}
												</span>
											)}
										</span>
										<span className="ml-2 flex shrink-0 items-center gap-3">
											{slot.persisted && (
												<button
													type="button"
													onClick={() => onStartEditSlot(slot)}
													className="text-xs text-brand-700 hover:underline"
												>
													{t("timeSlots.editButton")}
												</button>
											)}
											<button
												type="button"
												disabled={slot.persisted && removingSlotId === slot.id}
												onClick={() => {
													if (slot.persisted && slot.seriesId) {
														onRequestRemoveSeriesSlot(
															slot.id,
															slot.bookedCount,
														);
													} else if (slot.persisted) {
														onRemoveExistingSlot(slot.id);
													} else {
														onRemovePendingSlot(slot.id);
													}
												}}
												className="text-xs text-red-600 hover:underline disabled:opacity-50"
											>
												{slot.persisted && removingSlotId === slot.id
													? t("timeSlots.removing")
													: t("timeSlots.removeButton")}
											</button>
										</span>
									</li>
								),
							)}
						</ul>
					)}

					<div className="space-y-3 border-t border-gray-200 pt-3">
						<p className="text-xs font-semibold text-gray-700">
							{t("timeSlots.addTitle")}
						</p>
						<div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
							<div>
								<label
									htmlFor="slot-start"
									className="mb-1 block text-xs font-medium text-gray-600"
								>
									{t("timeSlots.fieldStart")}
								</label>
								<input
									id="slot-start"
									type="datetime-local"
									value={newSlot.startDateTime}
									min={
										!isEditMode
											? new Date(
													Date.now() - new Date().getTimezoneOffset() * 60000,
												)
													.toISOString()
													.slice(0, 16)
											: undefined
									}
									onChange={(e) =>
										onNewSlotChange({
											...newSlot,
											startDateTime: e.target.value,
										})
									}
									className={inputSurfaceClass}
								/>
							</div>
							<div>
								<label
									htmlFor="slot-end"
									className="mb-1 block text-xs font-medium text-gray-600"
								>
									{t("timeSlots.fieldEnd")}
								</label>
								<input
									id="slot-end"
									type="datetime-local"
									value={newSlot.endDateTime}
									onChange={(e) =>
										onNewSlotChange({
											...newSlot,
											endDateTime: e.target.value,
										})
									}
									className={inputSurfaceClass}
								/>
							</div>
						</div>
						<div>
							<label
								htmlFor="slot-max"
								className="mb-1 block text-xs font-medium text-gray-600"
							>
								{t("timeSlots.fieldMaxParticipants")}
							</label>
							<div className="flex items-center gap-3">
								<input
									id="slot-max"
									type="number"
									min={1}
									disabled={newSlot.maxParticipants === null}
									value={newSlot.maxParticipants ?? ""}
									onChange={(e) =>
										onNewSlotChange({
											...newSlot,
											maxParticipants: parseInt(e.target.value, 10) || 1,
										})
									}
									className="w-24 rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm shadow-sm transition focus:border-brand-400 disabled:bg-gray-100 disabled:text-gray-400"
								/>
								<label
									htmlFor="slot-unlimited"
									className="flex items-center gap-1.5 text-xs font-medium text-gray-600"
								>
									<input
										id="slot-unlimited"
										type="checkbox"
										checked={newSlot.maxParticipants === null}
										onChange={(e) =>
											onNewSlotChange({
												...newSlot,
												maxParticipants: e.target.checked ? null : 1,
											})
										}
										className="h-3.5 w-3.5 rounded border-gray-300 text-brand-600"
									/>
									{t("timeSlots.unlimited")}
								</label>
							</div>
						</div>
						{occurrence === "Recurring" && (
							<div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
								<div>
									<label
										htmlFor="slot-recurrence-frequency"
										className="mb-1 block text-xs font-medium text-gray-600"
									>
										{t("timeSlots.recurrenceFrequency")}
									</label>
									<Dropdown
										id="slot-recurrence-frequency"
										value={recurrenceFrequency}
										onChange={onRecurrenceFrequencyChange}
										className={inputSurfaceClass}
										options={[
											{
												value: "Weekly",
												label: t("timeSlots.recurrenceWeekly"),
											},
											{
												value: "Monthly",
												label: t("timeSlots.recurrenceMonthly"),
											},
										]}
									/>
								</div>
								<div>
									<label
										htmlFor="slot-recurrence-count"
										className="mb-1 block text-xs font-medium text-gray-600"
									>
										{t("timeSlots.recurrenceCount")}
									</label>
									<input
										id="slot-recurrence-count"
										type="number"
										min={1}
										max={52}
										value={recurrenceCount}
										onChange={(e) =>
											onRecurrenceCountChange(
												Math.max(
													1,
													Math.min(52, parseInt(e.target.value, 10) || 1),
												),
											)
										}
										className={inputSurfaceClass}
									/>
								</div>
							</div>
						)}
						{slotError && <p className="text-xs text-red-600">{slotError}</p>}
						<button
							type="button"
							disabled={
								addingSlot || !newSlot.startDateTime || !newSlot.endDateTime
							}
							onClick={onAddSlot}
							className="rounded-lg border border-brand-200 bg-white px-3 py-1.5 text-xs font-semibold text-brand-700 transition hover:bg-brand-50 disabled:opacity-50"
						>
							{addingSlot ? t("timeSlots.adding") : t("timeSlots.addButton")}
						</button>
					</div>
				</div>
			)}

			{!isScheduledSlots && (
				<div className="rounded-card border border-gray-200 bg-gray-50 p-4">
					<label
						htmlFor="create-valid-until"
						className={`mb-1.5 ${labelClass}`}
					>
						{t("createOpportunity.fieldValidUntil")}
					</label>
					<Controller
						name="validUntil"
						control={control}
						render={({ field }) => (
							<input
								id="create-valid-until"
								type="date"
								value={field.value}
								min={todayDateInputValue}
								onChange={(e) => field.onChange(e.target.value)}
								className={inputSurfaceClass}
							/>
						)}
					/>
					<p className="mt-1.5 text-xs text-gray-500">
						{t("createOpportunity.validUntilHint")}
					</p>
				</div>
			)}

			{error && (
				<ErrorBanner
					ref={errorRef}
					message={error}
					tabIndex={-1}
					className="focus:outline-none"
				/>
			)}
		</div>
	);
}
