import { useEffect, useMemo, useRef, useState } from "react";
import type { ChangeEvent } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { useTranslation } from "react-i18next";
import type {
	AddressDto,
	EinsatzbereitApi,
	TimeSlotDetail,
	VolunteerOpportunityDetails,
} from "../../client/api-client";
import { useApiClient } from "../../hooks/useApiClient";
import { dispatchToast } from "../../lib/toastBus";
import { getApiErrorMessage, isApiErrorCode } from "../../lib/apiError";
import ConfirmDialog from "../ConfirmDialog";
import Modal from "../Modal";
import Button from "../Button";
import ErrorBanner from "../ErrorBanner";
import ImageCropModal from "../ImageCropModal";
import { RequiredFieldsLegend } from "../RequiredMark";
import { Stepper } from "./shared";
import BasicsStep from "./BasicsStep";
import LocationStep from "./LocationStep";
import FormatStep from "./FormatStep";
import DetailsStep from "./DetailsStep";
import type { SeriesEditScope } from "./DetailsStep";
import DeleteSeriesSlotDialog from "./DeleteSeriesSlotDialog";
import { CloseIcon } from "../icons";
import {
	buildOpportunityFormSchema,
	errorStepsFromFieldErrors,
	STEP_FIELDS,
	TOTAL_STEPS,
} from "./schema";
import type { OpportunityFormValues } from "./schema";

const MAX_BANNER_BYTES = 2 * 1024 * 1024;
const BANNER_TYPES = ["image/jpeg", "image/png", "image/webp"];

/** Ties the refused-jump message to the step button that was refused. */
const BLOCKED_JUMP_MESSAGE_ID = "create-opportunity-step-blocked";

function advanceDate(
	origin: Date,
	frequency: string | undefined,
	steps: number,
): Date {
	const d = new Date(origin);
	if (frequency === "Weekly") {
		d.setDate(d.getDate() + 7 * steps);
	} else if (frequency === "Monthly") {
		d.setMonth(d.getMonth() + steps);
	}
	return d;
}

function resolveCheckInPin(
	values: Pick<OpportunityFormValues, "checkInMethod" | "checkInPin">,
): string | undefined {
	return values.checkInMethod === "PINCode"
		? values.checkInPin || undefined
		: undefined;
}

async function uploadBanner(
	api: EinsatzbereitApi,
	opportunityId: string,
	bannerFile: File,
	onError: () => void,
): Promise<void> {
	try {
		await api.uploadOpportunityBanner(opportunityId, {
			data: bannerFile,
			fileName: bannerFile.name,
		});
	} catch {
		onError();
	}
}

interface Props {
	organizationId: string;
	onClose: () => void;
	/**
	 * Called after a successful save. When a brand-new opportunity was saved as
	 * a draft, its id is passed so the dashboard can scroll to and highlight it
	 * in the Drafts section (publish/edit paths pass nothing).
	 */
	onSuccess: (createdDraftId?: string) => void;
	/** When provided the modal operates in edit mode. */
	initialOpportunity?: VolunteerOpportunityDetails;
}

interface PendingTimeSlot {
	id: string;
	/** Groups slots generated by one "Add" action so a still-unpublished
	 * recurring batch can be submitted as a single series-creating request
	 * instead of one independent call per occurrence (einsatzbereit#1058). */
	batchId: string;
	batchFrequency: string | undefined;
	batchCount: number;
	startDateTime: string;
	endDateTime: string;
	maxParticipants: number | null;
}

interface EditingSlot {
	id: string;
	startDateTime: string;
	endDateTime: string;
	maxParticipants: number | null;
	scope: SeriesEditScope;
}

/** Converts a Date (or ISO string) to the `YYYY-MM-DDTHH:mm` value a
 * `datetime-local` input expects, in the viewer's local time. */
function toDatetimeLocalValue(value: Date | string): string {
	const date = value instanceof Date ? value : new Date(value);
	return new Date(date.getTime() - date.getTimezoneOffset() * 60000)
		.toISOString()
		.slice(0, 16);
}

/** Converts a Date (or ISO string) to the `YYYY-MM-DD` value a `date`
 * input expects, in the viewer's local time. */
function toDateInputValue(value: Date | string): string {
	const date = value instanceof Date ? value : new Date(value);
	return new Date(date.getTime() - date.getTimezoneOffset() * 60000)
		.toISOString()
		.slice(0, 10);
}

/** Converts a `YYYY-MM-DD` date-input value to a Date at the end of that
 * local day, so the deadline stays valid through the entire chosen day
 * rather than expiring the instant it starts (einsatzbereit#1086). */
function endOfDayFromDateInput(value: string): Date {
	const [year, month, day] = value.split("-").map(Number);
	return new Date(year, month - 1, day, 23, 59, 59, 999);
}

const DEFAULT_VALUES: OpportunityFormValues = {
	title: "",
	description: "",
	isRemote: false,
	street: "",
	houseNumber: "",
	zipCode: "",
	city: "",
	occurrence: "OneTime",
	participationType: "ScheduledSlots",
	checkInMethod: "None",
	checkInPin: "",
	category: undefined,
	tags: [],
	validUntil: "",
};

function formFromOpportunity(
	opp: VolunteerOpportunityDetails,
): OpportunityFormValues {
	return {
		title: opp.title ?? "",
		description: opp.description ?? "",
		isRemote: opp.isRemote,
		street: opp.street ?? "",
		houseNumber: opp.houseNumber ?? "",
		zipCode: opp.zipCode ?? "",
		city: opp.city ?? "",
		occurrence: opp.occurrence as OpportunityFormValues["occurrence"],
		participationType:
			opp.participationType as OpportunityFormValues["participationType"],
		checkInMethod: opp.checkInMethod as OpportunityFormValues["checkInMethod"],
		checkInPin: "",
		category: opp.category ?? undefined,
		tags: opp.tags ?? [],
		validUntil: opp.validUntil ? toDateInputValue(opp.validUntil) : "",
	};
}

export default function CreateVolunteerOpportunityModal({
	organizationId,
	onClose,
	onSuccess,
	initialOpportunity,
}: Props) {
	const api = useApiClient();
	const { t } = useTranslation();
	const isEditMode = initialOpportunity !== undefined;
	// A Draft, and an Unpublished opportunity (taken off the public listing but
	// not re-validated the way Publish() would), accept lenient partial saves
	// from any step, same as during initial creation - the backend's own
	// Rename/ChangeDescription/Relocate only re-run publishability checks when
	// Status is Published (see VolunteerOpportunity.cs), so a Cancelled or
	// Published opportunity keeps the stricter validation on its single "Save"
	// button.
	const canSaveDraft =
		!isEditMode ||
		initialOpportunity.status === "Draft" ||
		initialOpportunity.status === "Unpublished";

	const schema = useMemo(() => buildOpportunityFormSchema(t), [t]);
	const {
		register,
		control,
		watch,
		setValue,
		getValues,
		trigger,
		clearErrors,
		formState: { errors, isDirty },
	} = useForm<OpportunityFormValues>({
		resolver: zodResolver(schema),
		mode: "onBlur",
		defaultValues: initialOpportunity
			? formFromOpportunity(initialOpportunity)
			: DEFAULT_VALUES,
	});

	const [step, setStep] = useState(1);
	const [submitting, setSubmitting] = useState<"draft" | "publish" | null>(
		null,
	);
	const [error, setError] = useState<string | null>(null);
	// Bumped on every submit attempt that sets `error`, even when the message
	// text is identical to the previous attempt (e.g. retrying without
	// changing anything) - lets DetailsStep re-scroll/re-focus the error each
	// time, since a dependency on the string alone wouldn't change.
	const [errorToken, setErrorToken] = useState(0);
	// Set when a stepper jump was refused because an earlier step is invalid:
	// `target` is the step that was clicked, `blocking` the first one standing
	// in its way. `attempt` is bumped on every refusal so an unchanged message
	// still re-mounts (and gets re-announced) on a repeat click, same reason as
	// `errorToken` above.
	const [blockedJump, setBlockedJump] = useState<{
		target: number;
		blocking: number;
		attempt: number;
	} | null>(null);
	const [orgAddress, setOrgAddress] = useState<AddressDto | null>(null);
	const [showDiscardConfirm, setShowDiscardConfirm] = useState(false);

	// Banner
	const [bannerFile, setBannerFile] = useState<File | null>(null);
	const [bannerPreview, setBannerPreview] = useState<string | null>(
		initialOpportunity?.bannerImageUrl ?? null,
	);
	const [bannerError, setBannerError] = useState<string | null>(null);
	const [bannerRemoved, setBannerRemoved] = useState(false);
	const [croppingBannerFile, setCroppingBannerFile] = useState<File | null>(
		null,
	);

	// Time slots: pending = not yet persisted (create mode); existing = already saved (edit mode)
	const [pendingSlots, setPendingSlots] = useState<PendingTimeSlot[]>([]);
	const [existingSlots, setExistingSlots] = useState<TimeSlotDetail[]>(
		initialOpportunity?.timeSlots ?? [],
	);
	const [newSlot, setNewSlot] = useState<{
		startDateTime: string;
		endDateTime: string;
		maxParticipants: number | null;
	}>({
		startDateTime: "",
		endDateTime: "",
		maxParticipants: 1,
	});
	const [slotError, setSlotError] = useState<string | null>(null);
	const [removingSlotId, setRemovingSlotId] = useState<string | null>(null);
	const [addingSlot, setAddingSlot] = useState(false);
	const [editingSlot, setEditingSlot] = useState<EditingSlot | null>(null);
	const [updatingSlotId, setUpdatingSlotId] = useState<string | null>(null);
	const [pendingSlotEdit, setPendingSlotEdit] = useState<
		(EditingSlot & { bookedCount: number }) | null
	>(null);
	const [pendingSeriesDelete, setPendingSeriesDelete] = useState<{
		id: string;
		bookedCount: number;
	} | null>(null);
	const [deletingSeriesSlot, setDeletingSeriesSlot] = useState(false);
	const [seriesDeleteError, setSeriesDeleteError] = useState<string | null>(
		null,
	);
	const [recurrenceFrequency, setRecurrenceFrequency] = useState("Weekly");
	const [recurrenceCount, setRecurrenceCount] = useState(1);

	// Create mode only: once the draft opportunity is persisted, its id is
	// kept here (not in state) for the lifetime of this modal instance. If a
	// later step (banner, a time slot, publish) throws and the user retries
	// via the same button, `submit` reuses this id instead of calling
	// `createVolunteerOpportunity` again - which would otherwise create a
	// second, duplicate draft (#1227). `createdSlotIdsRef` mirrors this for
	// individually-submitted time slots (a batch a user partially removed
	// rows from, see PendingTimeSlot) so a retry only creates the ones still
	// missing; `createdBatchIdsRef` does the same at batch granularity for a
	// still-intact recurring batch submitted as one atomic bulk-create call
	// (einsatzbereit#1058) - that call either fully succeeds or fully fails,
	// so per-batch tracking is the correct (and only meaningful) grain there.
	const createdOpportunityIdRef = useRef<string | null>(null);
	const createdSlotIdsRef = useRef<Set<string>>(new Set());
	const createdBatchIdsRef = useRef<Set<string>>(new Set());

	const bodyRef = useRef<HTMLDivElement>(null);

	const occurrence = watch("occurrence");
	const participationType = watch("participationType");
	const isRemote = watch("isRemote");
	const isScheduledSlots = participationType === "ScheduledSlots";

	useEffect(() => {
		if (isEditMode) return;
		let cancelled = false;
		api
			.getOrganizationDetails(organizationId)
			.then((org) => {
				if (cancelled || !org.address) return;
				setOrgAddress(org.address);
				const current = getValues();
				if (
					!current.street &&
					!current.houseNumber &&
					!current.zipCode &&
					!current.city
				) {
					setValue("street", org.address.street ?? "");
					setValue("houseNumber", org.address.houseNumber ?? "");
					setValue("zipCode", org.address.zipCode ?? "");
					setValue("city", org.address.city ?? "");
				}
			})
			.catch(() => {});
		return () => {
			cancelled = true;
		};
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, [organizationId, isEditMode]);

	useEffect(() => {
		if (!initialOpportunity || initialOpportunity.checkInMethod !== "PINCode")
			return;
		let cancelled = false;
		api
			.getOpportunityCheckInPin(initialOpportunity.id)
			.then((pin) => {
				if (cancelled || !pin) return;
				setValue("checkInPin", pin);
			})
			.catch(() => {});
		return () => {
			cancelled = true;
		};
		// eslint-disable-next-line react-hooks/exhaustive-deps
	}, [initialOpportunity]);

	useEffect(() => {
		return () => {
			if (bannerPreview) URL.revokeObjectURL(bannerPreview);
		};
	}, [bannerPreview]);

	// Any navigation that did go through retires the refusal message.
	useEffect(() => {
		setBlockedJump(null);
	}, [step]);

	function requestClose() {
		// isDirty only tracks react-hook-form's own fields - time slots, the
		// banner file and its removal all live in separate useState outside the
		// form, so a wizard that only touched those (e.g. added slots on step 4
		// without editing a text field) needs its own check too, or the discard
		// guard fails to guard the very thing it exists for (#1233).
		const hasUnsavedChanges =
			isDirty ||
			pendingSlots.length > 0 ||
			bannerFile !== null ||
			bannerRemoved;
		if (hasUnsavedChanges) setShowDiscardConfirm(true);
		else onClose();
	}

	function applyOrgAddress() {
		if (!orgAddress) return;
		setValue("street", orgAddress.street);
		setValue("houseNumber", orgAddress.houseNumber);
		setValue("zipCode", orgAddress.zipCode);
		setValue("city", orgAddress.city);
		clearErrors(["street", "houseNumber", "zipCode", "city"]);
	}

	function handleRemoteToggle(checked: boolean) {
		if (checked) clearErrors(["street", "houseNumber", "zipCode", "city"]);
	}

	function setCheckInPin(pin: string) {
		setValue("checkInPin", pin, { shouldDirty: true });
	}

	async function handleNext() {
		const fields = STEP_FIELDS[step];
		const valid = fields.length === 0 || (await trigger(fields));
		if (!valid) return;
		setStep((s) => Math.min(TOTAL_STEPS, s + 1));
	}

	async function handleStepClick(n: number) {
		if (n <= step) {
			setStep(n);
			return;
		}
		// Jumping ahead skips every step in between - validate all of their
		// fields, not just the currently active one, so a step revisited and
		// broken (e.g. going back to blank out the title) still blocks the
		// jump instead of only surfacing at Publish-time. Validating one step
		// at a time rather than one trigger() over the union of their fields
		// still paints every offending step's rule red, and additionally tells
		// us *which* step to name below.
		let blocking: number | null = null;
		for (let s = step; s < n; s++) {
			const fields = STEP_FIELDS[s];
			if (fields.length === 0) continue;
			if (!(await trigger(fields)) && blocking === null) blocking = s;
		}
		if (blocking !== null) {
			// Refusing in silence left the reason to be inferred from a field
			// turning red - and the offending field can sit on a step that
			// isn't even rendered, leaving nothing but an unexplained red rule
			// somewhere in the stepper (#1782). Name the step that blocks the
			// jump instead.
			const blockingStep = blocking;
			setBlockedJump((prev) => ({
				target: n,
				blocking: blockingStep,
				attempt: (prev?.attempt ?? 0) + 1,
			}));
			return;
		}
		setStep(n);
	}

	function handleBannerChange(e: ChangeEvent<HTMLInputElement>) {
		const file = e.target.files?.[0];
		e.target.value = "";
		if (!file) return;
		if (!BANNER_TYPES.includes(file.type)) {
			setBannerError(t("createOpportunity.bannerWrongType"));
			return;
		}
		if (file.size > MAX_BANNER_BYTES) {
			setBannerError(t("createOpportunity.bannerTooLarge"));
			return;
		}
		setBannerError(null);
		setCroppingBannerFile(file);
	}

	function handleBannerCropped(croppedFile: File) {
		setCroppingBannerFile(null);
		setBannerFile(croppedFile);
		setBannerPreview(URL.createObjectURL(croppedFile));
	}

	function removeBanner() {
		if (isEditMode && bannerFile === null) {
			setBannerRemoved(true);
		}
		setBannerFile(null);
		setBannerPreview(null);
		setBannerError(null);
	}

	async function handleAddSlot() {
		if (!newSlot.startDateTime || !newSlot.endDateTime) return;
		setSlotError(null);
		const start = new Date(newSlot.startDateTime);
		const end = new Date(newSlot.endDateTime);
		if (end <= start) {
			setSlotError(t("timeSlots.addError"));
			return;
		}

		const isRecurring = occurrence === "Recurring";
		if (isEditMode && initialOpportunity) {
			setAddingSlot(true);
			try {
				const responses = await api.createTimeSlot(initialOpportunity.id, {
					startDateTime: start,
					endDateTime: end,
					maxParticipants: newSlot.maxParticipants ?? undefined,
					recurrenceFrequency: isRecurring ? recurrenceFrequency : undefined,
					recurrenceCount: isRecurring ? recurrenceCount : 1,
				});
				setExistingSlots((prev) => [
					...prev,
					...responses.map((r) => ({
						id: r.id,
						startDateTime: r.startDateTime,
						endDateTime: r.endDateTime,
						maxParticipants: r.maxParticipants,
						bookedCount: 0,
						seriesId: r.seriesId,
						recurrenceFrequency: r.recurrenceFrequency,
						recurrenceCount: r.recurrenceCount,
					})),
				]);
				// Only cleared on success (#1241) - on failure the organizer would
				// otherwise have to re-enter the whole slot, recurrence included,
				// to retry.
				setNewSlot({ startDateTime: "", endDateTime: "", maxParticipants: 1 });
			} catch {
				setSlotError(t("timeSlots.addError"));
			} finally {
				setAddingSlot(false);
			}
		} else {
			const duration = end.getTime() - start.getTime();
			const count = isRecurring
				? Math.max(1, Math.min(52, recurrenceCount))
				: 1;
			const freq = isRecurring ? recurrenceFrequency : undefined;
			const batchId = crypto.randomUUID();
			const newSlots: PendingTimeSlot[] = Array.from(
				{ length: count },
				(_, i) => {
					const slotStart = advanceDate(start, freq, i);
					const slotEnd = new Date(slotStart.getTime() + duration);
					return {
						id: crypto.randomUUID(),
						batchId,
						batchFrequency: freq,
						batchCount: count,
						startDateTime: slotStart.toISOString(),
						endDateTime: slotEnd.toISOString(),
						maxParticipants: newSlot.maxParticipants,
					};
				},
			);
			setPendingSlots((prev) => [...prev, ...newSlots]);
			setNewSlot({ startDateTime: "", endDateTime: "", maxParticipants: 1 });
		}
	}

	function handleRemovePendingSlot(id: string) {
		setPendingSlots((prev) => prev.filter((s) => s.id !== id));
	}

	async function handleRemoveExistingSlot(timeSlotId: string) {
		if (!initialOpportunity) return;
		setRemovingSlotId(timeSlotId);
		setSlotError(null);
		try {
			await api.deleteTimeSlot(initialOpportunity.id, timeSlotId, "Only");
			setExistingSlots((prev) => prev.filter((s) => s.id !== timeSlotId));
		} catch {
			setSlotError(t("timeSlots.removeError"));
		} finally {
			setRemovingSlotId(null);
		}
	}

	function handleRequestRemoveSeriesSlot(
		timeSlotId: string,
		bookedCount: number,
	) {
		setSeriesDeleteError(null);
		setPendingSeriesDelete({ id: timeSlotId, bookedCount });
	}

	async function performSeriesDelete(scope: SeriesEditScope) {
		if (!initialOpportunity || !pendingSeriesDelete) return;
		setDeletingSeriesSlot(true);
		setSeriesDeleteError(null);
		try {
			const result = await api.deleteTimeSlot(
				initialOpportunity.id,
				pendingSeriesDelete.id,
				scope,
			);
			setExistingSlots((prev) =>
				prev.filter((s) => !result.deletedTimeSlotIds.includes(s.id)),
			);
			setPendingSeriesDelete(null);
		} catch {
			setSeriesDeleteError(t("timeSlots.removeError"));
		} finally {
			setDeletingSeriesSlot(false);
		}
	}

	function handleStartEditSlot(slot: {
		id: string;
		startDateTime: string;
		endDateTime: string;
		maxParticipants: number | null;
	}) {
		setSlotError(null);
		setEditingSlot({
			id: slot.id,
			startDateTime: toDatetimeLocalValue(slot.startDateTime),
			endDateTime: toDatetimeLocalValue(slot.endDateTime),
			maxParticipants: slot.maxParticipants,
			scope: "Only",
		});
	}

	async function applySlotEdit(edit: EditingSlot) {
		if (!initialOpportunity) return;
		setUpdatingSlotId(edit.id);
		setSlotError(null);
		try {
			const result = await api.updateTimeSlot(initialOpportunity.id, edit.id, {
				startDateTime:
					edit.scope === "Only" ? new Date(edit.startDateTime) : undefined,
				endDateTime:
					edit.scope === "Only" ? new Date(edit.endDateTime) : undefined,
				maxParticipants: edit.maxParticipants ?? undefined,
				scope: edit.scope,
			});
			if (edit.scope === "Only") {
				setExistingSlots((prev) =>
					prev.map((s) =>
						s.id === edit.id
							? {
									...s,
									startDateTime: new Date(edit.startDateTime),
									endDateTime: new Date(edit.endDateTime),
									maxParticipants: edit.maxParticipants ?? undefined,
								}
							: s,
					),
				);
			} else {
				const fresh = await api.getVolunteerOpportunityDetails(
					initialOpportunity.id,
				);
				setExistingSlots(fresh.timeSlots);
				if (result.skippedTimeSlotIds.length > 0) {
					setSlotError(
						t("timeSlots.editPartialSkip", {
							count: result.skippedTimeSlotIds.length,
						}),
					);
				}
			}
			setEditingSlot(null);
		} catch {
			setSlotError(t("timeSlots.editError"));
		} finally {
			setUpdatingSlotId(null);
			setPendingSlotEdit(null);
		}
	}

	function handleRequestSaveEditSlot(bookedCount: number) {
		if (!editingSlot) return;
		if (editingSlot.scope !== "Only") {
			setSlotError(null);
			void applySlotEdit(editingSlot);
			return;
		}
		if (!editingSlot.startDateTime || !editingSlot.endDateTime) return;
		const start = new Date(editingSlot.startDateTime);
		const end = new Date(editingSlot.endDateTime);
		if (end <= start) {
			setSlotError(t("timeSlots.editError"));
			return;
		}
		setSlotError(null);
		if (bookedCount > 0) {
			setPendingSlotEdit({ ...editingSlot, bookedCount });
		} else {
			void applySlotEdit(editingSlot);
		}
	}

	const submit = async (asDraft: boolean) => {
		if (!asDraft) {
			// Walk the steps in order and stop at the first one that fails -
			// its own `trigger()` return value is used directly rather than
			// reading `errors` afterward, which can still reflect the render
			// this closure was created in rather than the just-awaited result.
			for (let s = 1; s <= TOTAL_STEPS; s++) {
				const fields = STEP_FIELDS[s];
				if (fields.length === 0) continue;
				const stepValid = await trigger(fields);
				if (!stepValid) {
					setStep(s);
					return;
				}
			}
		}

		const values = getValues();
		if (!asDraft && values.participationType === "ScheduledSlots") {
			const totalSlots = pendingSlots.length + existingSlots.length;
			if (totalSlots === 0) {
				setError(t("timeSlots.requiredForPublish"));
				setErrorToken((tk) => tk + 1);
				setStep(4);
				return;
			}
		}
		if (
			!asDraft &&
			values.participationType === "IndividualContact" &&
			!values.validUntil
		) {
			setError(t("createOpportunity.validUntilRequiredForPublish"));
			setErrorToken((tk) => tk + 1);
			setStep(4);
			return;
		}
		setSubmitting(asDraft ? "draft" : "publish");
		setError(null);
		// Set only on the create-as-draft path so the dashboard knows which
		// freshly saved draft to reveal in its Drafts section.
		let createdDraftId: string | undefined;
		try {
			if (isEditMode && initialOpportunity) {
				await api.updateVolunteerOpportunity(initialOpportunity.id, {
					title: values.title,
					description: values.description,
					isRemote: values.isRemote,
					street: values.isRemote ? undefined : values.street,
					houseNumber: values.isRemote ? undefined : values.houseNumber,
					zipCode: values.isRemote ? undefined : values.zipCode,
					city: values.isRemote ? undefined : values.city,
					occurrence: values.occurrence,
					participationType: values.participationType,
					checkInMethod: values.checkInMethod,
					checkInPin: resolveCheckInPin(values),
					category: values.category || undefined,
					tags: values.tags,
					validUntil: values.validUntil
						? endOfDayFromDateInput(values.validUntil)
						: undefined,
				});
				if (bannerFile) {
					await uploadBanner(api, initialOpportunity.id, bannerFile, () =>
						dispatchToast("error", t("editOpportunity.bannerUploadFailed")),
					);
				} else if (bannerRemoved) {
					try {
						await api.deleteOpportunityBanner(initialOpportunity.id);
					} catch {
						dispatchToast("error", t("editOpportunity.bannerRemoveFailed"));
					}
				}
			} else {
				// A ScheduledSlots opportunity can't be published until it has at
				// least one time slot, and slots can only be added after the
				// opportunity exists. Always create it as a draft, add slots and
				// banner, then publish - this also keeps it invisible in listings
				// if any step in between fails, instead of leaving a published
				// dead-end.
				const publishScheduledSlotsAfterCreate = !asDraft && isScheduledSlots;

				// If a previous attempt already created the draft but failed on a
				// later step, reuse that id and update it instead of creating a
				// second opportunity - createVolunteerOpportunity/createTimeSlot
				// have no dedup on the backend, so calling either twice for the
				// same logical attempt produces duplicates (#1227).
				let opportunityId = createdOpportunityIdRef.current;
				if (opportunityId) {
					await api.updateVolunteerOpportunity(opportunityId, {
						title: values.title,
						description: values.description,
						isRemote: values.isRemote,
						street: values.isRemote ? undefined : values.street,
						houseNumber: values.isRemote ? undefined : values.houseNumber,
						zipCode: values.isRemote ? undefined : values.zipCode,
						city: values.isRemote ? undefined : values.city,
						occurrence: values.occurrence,
						participationType: values.participationType,
						checkInMethod: values.checkInMethod,
						checkInPin: resolveCheckInPin(values),
						category: values.category || undefined,
						tags: values.tags,
						validUntil: values.validUntil
							? endOfDayFromDateInput(values.validUntil)
							: undefined,
					});
				} else {
					const opportunity = await api.createVolunteerOpportunity({
						title: values.title,
						description: values.description,
						organizationId,
						isRemote: values.isRemote,
						street: values.isRemote ? undefined : values.street,
						houseNumber: values.isRemote ? undefined : values.houseNumber,
						zipCode: values.isRemote ? undefined : values.zipCode,
						city: values.isRemote ? undefined : values.city,
						occurrence: values.occurrence,
						participationType: values.participationType,
						checkInMethod: values.checkInMethod,
						checkInPin: resolveCheckInPin(values),
						category: values.category,
						tags: values.tags,
						validUntil: values.validUntil
							? endOfDayFromDateInput(values.validUntil)
							: undefined,
						isDraft: asDraft || publishScheduledSlotsAfterCreate,
					});
					opportunityId = opportunity.id;
					createdOpportunityIdRef.current = opportunityId;
				}
				if (bannerFile) {
					await uploadBanner(api, opportunityId, bannerFile, () =>
						dispatchToast("error", t("createOpportunity.bannerUploadFailed")),
					);
				}
				// Submit one recurring create request per still-intact batch (see
				// PendingTimeSlot) so the backend can stamp a shared SeriesId
				// (einsatzbereit#1058) - a batch a user has partially removed rows
				// from no longer forms a clean recurrence, so those fall back to
				// one independent create per remaining occurrence. Already-created
				// batches/slots from a prior failed attempt are skipped on retry
				// rather than recreated (#1227).
				const batches = new Map<string, PendingTimeSlot[]>();
				for (const slot of pendingSlots) {
					const list = batches.get(slot.batchId) ?? [];
					list.push(slot);
					batches.set(slot.batchId, list);
				}
				for (const [batchId, batchSlots] of batches) {
					const sorted = [...batchSlots].sort((a, b) =>
						a.startDateTime.localeCompare(b.startDateTime),
					);
					const first = sorted[0];
					const isIntactRecurringBatch =
						first.batchCount > 1 && sorted.length === first.batchCount;
					if (isIntactRecurringBatch) {
						if (createdBatchIdsRef.current.has(batchId)) continue;
						await api.createTimeSlot(opportunityId, {
							startDateTime: new Date(first.startDateTime),
							endDateTime: new Date(first.endDateTime),
							maxParticipants: first.maxParticipants ?? undefined,
							recurrenceFrequency: first.batchFrequency,
							recurrenceCount: first.batchCount,
						});
						createdBatchIdsRef.current.add(batchId);
					} else {
						for (const slot of sorted) {
							if (createdSlotIdsRef.current.has(slot.id)) continue;
							await api.createTimeSlot(opportunityId, {
								startDateTime: new Date(slot.startDateTime),
								endDateTime: new Date(slot.endDateTime),
								maxParticipants: slot.maxParticipants ?? undefined,
								recurrenceFrequency: undefined,
								recurrenceCount: 1,
							});
							createdSlotIdsRef.current.add(slot.id);
						}
					}
				}
				if (publishScheduledSlotsAfterCreate) {
					try {
						await api.publishVolunteerOpportunity(opportunityId);
					} catch (publishErr) {
						// Publish isn't idempotent on the backend (a second call 409s
						// with AlreadyPublished) - if a retry lands here after a prior
						// attempt's publish call actually succeeded, treat that as the
						// success it already is instead of surfacing a confusing error.
						if (
							!isApiErrorCode(
								publishErr,
								"VolunteerOpportunity.AlreadyPublished",
							)
						) {
							throw publishErr;
						}
					}
				}
				if (asDraft) {
					createdDraftId = opportunityId;
					dispatchToast("success", t("createOpportunity.draftSavedToast"));
				}
			}
			onSuccess(createdDraftId);
			onClose();
		} catch (err: unknown) {
			setError(
				getApiErrorMessage(
					err,
					isEditMode
						? t("editOpportunity.unknownError")
						: t("createOpportunity.unknownError"),
				),
			);
			setErrorToken((tk) => tk + 1);
		} finally {
			setSubmitting(null);
		}
	};

	const erroredFields = new Set(
		Object.keys(errors) as (keyof OpportunityFormValues)[],
	);
	const errorSteps = errorStepsFromFieldErrors(erroredFields);

	const stepTitles = [
		t("createOpportunity.step1Title"),
		t("createOpportunity.step2Title"),
		t("createOpportunity.step3Title"),
		t("createOpportunity.step4Title"),
	];
	// Only while the named step is in fact still invalid: fixing the field
	// (revalidated on blur) retires the message on its own, without the user
	// having to click the step again to find out whether it would work now.
	const blockedJumpMessage =
		blockedJump && errorSteps.has(blockedJump.blocking)
			? t("createOpportunity.stepBlocked", {
					target: blockedJump.target,
					blocking: blockedJump.blocking,
					blockingTitle: stepTitles[blockedJump.blocking - 1],
				})
			: null;

	const stepSubtitles = [
		t("createOpportunity.step1Subtitle"),
		t("createOpportunity.step2Subtitle"),
		t("createOpportunity.step3Subtitle"),
		isScheduledSlots
			? t("createOpportunity.step4SubtitleWaitlist")
			: t("createOpportunity.step4SubtitleIndividualContact"),
	];

	// Position of each slot within its series (1-based, ordered by start time)
	// for the "3/8" badge - computed client-side since the backend only stores
	// the total count, not each row's rank.
	const seriesPositionById = new Map<string, number>();
	if (isEditMode) {
		const bySeriesId = new Map<string, typeof existingSlots>();
		for (const s of existingSlots) {
			if (!s.seriesId) continue;
			const list = bySeriesId.get(s.seriesId) ?? [];
			list.push(s);
			bySeriesId.set(s.seriesId, list);
		}
		for (const slots of bySeriesId.values()) {
			slots
				.slice()
				.sort(
					(a, b) =>
						new Date(a.startDateTime).getTime() -
						new Date(b.startDateTime).getTime(),
				)
				.forEach((s, i) => seriesPositionById.set(s.id, i + 1));
		}
	}

	const allTimeSlots = isEditMode
		? existingSlots.map((s) => ({
				id: s.id,
				startDateTime:
					s.startDateTime instanceof Date
						? s.startDateTime.toISOString()
						: String(s.startDateTime),
				endDateTime:
					s.endDateTime instanceof Date
						? s.endDateTime.toISOString()
						: String(s.endDateTime),
				maxParticipants: s.maxParticipants ?? null,
				bookedCount: s.bookedCount,
				persisted: true as const,
				seriesId: s.seriesId,
				recurrenceFrequency: s.recurrenceFrequency,
				recurrenceCount: s.recurrenceCount,
				seriesPosition: s.seriesId ? seriesPositionById.get(s.id) : undefined,
			}))
		: pendingSlots.map((s) => ({
				...s,
				bookedCount: 0,
				persisted: false as const,
			}));

	return (
		<>
			<Modal
				onClose={requestClose}
				labelledBy="create-opportunity-dialog-title"
				maxWidth="max-w-xl"
				className="flex min-w-0 flex-col overflow-hidden rounded-card bg-white shadow-modal"
				suspended={
					showDiscardConfirm ||
					pendingSlotEdit !== null ||
					pendingSeriesDelete !== null ||
					croppingBannerFile !== null
				}
				initialFocusRef={bodyRef}
			>
				{/* Unlike the app's other (single-step) modals, this one is a multi-step
				wizard - the footer's "Back"/"Cancel" button changes meaning across
				steps, so this is the only modal with a dedicated header close (X)
				button giving a step-independent way out. */}
				<div className="flex items-center justify-between gap-4 border-b border-gray-100 px-6 py-4">
					<h2
						id="create-opportunity-dialog-title"
						className="text-lg font-semibold text-gray-900"
					>
						{isEditMode
							? t("createOpportunity.editTitle")
							: t("createOpportunity.title")}
					</h2>
					<button
						type="button"
						onClick={requestClose}
						aria-label={t("createOpportunity.cancel")}
						className="shrink-0 rounded-lg p-1.5 text-gray-600 transition-colors hover:bg-gray-100 hover:text-gray-800"
					>
						<CloseIcon className="h-5 w-5" />
					</button>
				</div>

				{/* Stepper lives in its own row in the body, not the header. */}
				<div className="border-b border-gray-100 px-6 pt-3 pb-3">
					<Stepper
						current={step}
						errorSteps={errorSteps}
						onStepClick={(n) => void handleStepClick(n)}
						steps={stepTitles}
						stepLabel={(n, label) =>
							`${t("createOpportunity.stepOf", { current: n, total: TOTAL_STEPS })}: ${label}`
						}
						blocked={
							blockedJump && blockedJumpMessage
								? {
										step: blockedJump.target,
										messageId: BLOCKED_JUMP_MESSAGE_ID,
									}
								: undefined
						}
					/>
					{blockedJump && blockedJumpMessage && (
						// Keyed on the attempt counter so a repeat click on the same
						// still-blocked step re-inserts the alert - an assertive live
						// region whose text didn't change is not re-announced.
						<ErrorBanner
							key={blockedJump.attempt}
							id={BLOCKED_JUMP_MESSAGE_ID}
							message={blockedJumpMessage}
							className="mt-3"
						/>
					)}
				</div>

				{/* Announces the active step to screen readers whenever it changes. */}
				<div aria-live="polite" className="sr-only">
					{t("createOpportunity.stepOf", { current: step, total: TOTAL_STEPS })}
					: {stepTitles[step - 1]}
				</div>

				<div
					ref={bodyRef}
					className="max-h-[min(70vh,640px)] overflow-y-auto px-6 py-5"
				>
					<h3 className="sr-only">{stepTitles[step - 1]}</h3>
					<p className="mb-4 text-sm leading-relaxed text-gray-500">
						{stepSubtitles[step - 1]}
					</p>

					{/* Only steps 1 and 2 carry required fields, and step 2's are the
					address ones - a remote opportunity has none, so the legend would
					explain an asterisk that isn't on screen. */}
					{(step === 1 || (step === 2 && !isRemote)) && (
						<RequiredFieldsLegend className="-mt-2 mb-4" />
					)}

					{step === 1 && (
						<BasicsStep
							register={register}
							watch={watch}
							titleError={errors.title?.message}
							descriptionError={errors.description?.message}
							bannerPreview={bannerPreview}
							bannerError={bannerError}
							onBannerChange={handleBannerChange}
							onBannerRemove={removeBanner}
						/>
					)}

					{step === 2 && (
						<LocationStep
							register={register}
							watch={watch}
							onRemoteToggle={handleRemoteToggle}
							errors={{
								street: errors.street?.message,
								houseNumber: errors.houseNumber?.message,
								zipCode: errors.zipCode?.message,
								city: errors.city?.message,
							}}
							organizationId={organizationId}
							orgAddress={orgAddress}
							isEditMode={isEditMode}
							onApplyOrgAddress={applyOrgAddress}
						/>
					)}

					{step === 3 && (
						<FormatStep
							register={register}
							watch={watch}
							setCheckInPin={setCheckInPin}
							checkInPinError={errors.checkInPin?.message}
						/>
					)}

					{step === 4 && (
						<DetailsStep
							control={control}
							isScheduledSlots={isScheduledSlots}
							occurrence={occurrence}
							isEditMode={isEditMode}
							allTimeSlots={allTimeSlots}
							removingSlotId={removingSlotId}
							onRemoveExistingSlot={(id) => void handleRemoveExistingSlot(id)}
							onRequestRemoveSeriesSlot={handleRequestRemoveSeriesSlot}
							onRemovePendingSlot={handleRemovePendingSlot}
							editingSlot={editingSlot}
							onStartEditSlot={handleStartEditSlot}
							onEditingSlotChange={setEditingSlot}
							onCancelEditSlot={() => setEditingSlot(null)}
							onSaveEditSlot={handleRequestSaveEditSlot}
							updatingSlotId={updatingSlotId}
							newSlot={newSlot}
							onNewSlotChange={setNewSlot}
							slotError={slotError}
							addingSlot={addingSlot}
							onAddSlot={() => void handleAddSlot()}
							recurrenceFrequency={recurrenceFrequency}
							onRecurrenceFrequencyChange={setRecurrenceFrequency}
							recurrenceCount={recurrenceCount}
							onRecurrenceCountChange={setRecurrenceCount}
							error={error}
							errorToken={errorToken}
						/>
					)}
				</div>

				<div className="flex items-center justify-between gap-3 border-t border-gray-100 bg-gray-50 px-6 py-4">
					<Button
						type="button"
						variant="secondary"
						data-testid="modal-cancel"
						onClick={() => (step > 1 ? setStep((s) => s - 1) : requestClose())}
					>
						{step === 1
							? t("createOpportunity.cancel")
							: t("createOpportunity.back")}
					</Button>

					<div className="flex items-center gap-2">
						{canSaveDraft && (
							<Button
								type="button"
								variant="tertiary"
								data-testid="modal-save-draft"
								disabled={submitting !== null}
								onClick={() => void submit(true)}
							>
								{submitting === "draft"
									? t("createOpportunity.savingDraft")
									: t("createOpportunity.saveDraft")}
							</Button>
						)}
						{step < TOTAL_STEPS ? (
							<Button
								type="button"
								data-testid="modal-next"
								onClick={() => void handleNext()}
							>
								{t("createOpportunity.next")}
							</Button>
						) : (
							<Button
								type="button"
								disabled={submitting !== null}
								data-testid="modal-submit"
								onClick={() => void submit(false)}
							>
								{submitting === "publish"
									? isEditMode
										? t("createOpportunity.saving")
										: t("createOpportunity.creating")
									: isEditMode
										? t("createOpportunity.save")
										: t("createOpportunity.publish")}
							</Button>
						)}
					</div>
				</div>
			</Modal>

			{showDiscardConfirm && (
				<ConfirmDialog
					title={t("createOpportunity.unsavedChangesTitle")}
					message={t("createOpportunity.unsavedChangesMessage")}
					confirmLabel={t("createOpportunity.discardChanges")}
					onConfirm={() => {
						setShowDiscardConfirm(false);
						onClose();
					}}
					onClose={() => setShowDiscardConfirm(false)}
				/>
			)}

			{pendingSlotEdit && (
				<ConfirmDialog
					title={t("confirmDialog.editTimeSlot.title")}
					message={t("confirmDialog.editTimeSlot.message", {
						count: pendingSlotEdit.bookedCount,
					})}
					confirmLabel={t("confirmDialog.editTimeSlot.confirm")}
					loading={updatingSlotId === pendingSlotEdit.id}
					onConfirm={() => void applySlotEdit(pendingSlotEdit)}
					onClose={() => setPendingSlotEdit(null)}
				/>
			)}

			{pendingSeriesDelete && (
				<DeleteSeriesSlotDialog
					bookedCount={pendingSeriesDelete.bookedCount}
					loading={deletingSeriesSlot}
					error={seriesDeleteError}
					onConfirm={(scope) => void performSeriesDelete(scope)}
					onClose={() => setPendingSeriesDelete(null)}
				/>
			)}

			{croppingBannerFile && (
				<ImageCropModal
					file={croppingBannerFile}
					aspectRatio={2.5}
					shape="rect"
					outputWidth={1200}
					outputHeight={480}
					title={t("createOpportunity.fieldBanner")}
					onCancel={() => setCroppingBannerFile(null)}
					onCropped={handleBannerCropped}
				/>
			)}
		</>
	);
}
