parent=base
import=common/keycloak
locales=de,en
styles=css/einsatzbereit.css

kcFormGroupClass=form-group
kcLabelWrapperClass=form-label-wrapper
kcLabelClass=form-label
kcInputWrapperClass=form-input-wrapper
kcInputClass=form-input
kcInputGroup=input-group
kcInputErrorMessageClass=form-error
kcFormOptionsClass=form-options
kcFormOptionsWrapperClass=form-options-wrapper
kcFormSettingClass=form-setting
kcButtonClass=btn
kcButtonPrimaryClass=btn-primary
kcButtonDefaultClass=btn-secondary
kcButtonBlockClass=btn-block
kcButtonLargeClass=btn-lg
kcFormPasswordVisibilityButtonClass=btn-password-toggle
kcFormPasswordVisibilityIconShow=icon-eye
kcFormPasswordVisibilityIconHide=icon-eye-off
kcFormClass=auth-form
kcFormButtonsClass=form-buttons
