using Domain.Primitives;

namespace Domain.VolunteerOpportunities;

public sealed class TimeSlot
	: Entity<TimeSlotId>,
		IAuditableEntity
{
	public DateTimeOffset StartDateTime { get; private set; }

	public DateTimeOffset EndDateTime { get; private set; }

	/// <summary>Null means unlimited capacity - no cap on active sign-ups for this slot.</summary>
	public int? MaxParticipants { get; private set; }

	/// <summary>
	/// Groups the occurrences generated by a single recurring-creation request
	/// (see CreateTimeSlotCommandHandler) so they can later be edited or
	/// cancelled as a series instead of one-by-one (einsatzbereit#1058). Null
	/// for a standalone, non-recurring time slot.
	/// </summary>
	public Guid? SeriesId { get; private set; }

	public string? RecurrenceFrequency { get; private set; }

	public int? RecurrenceCount { get; private set; }

	public DateTimeOffset CreatedOn { get; private set; }

	public DateTimeOffset? ModifiedOn { get; private set; }

#pragma warning disable CS8618
	private TimeSlot() : base(default) { }
#pragma warning restore CS8618

	private TimeSlot(
		TimeSlotId id,
		DateTimeOffset startDateTime,
		DateTimeOffset endDateTime,
		int? maxParticipants,
		Guid? seriesId,
		string? recurrenceFrequency,
		int? recurrenceCount)
		: base(id)
	{
		StartDateTime = startDateTime;
		EndDateTime = endDateTime;
		MaxParticipants = maxParticipants;
		SeriesId = seriesId;
		RecurrenceFrequency = recurrenceFrequency;
		RecurrenceCount = recurrenceCount;
	}

	public static Result<TimeSlot> Create(
		DateTimeOffset startDateTime,
		DateTimeOffset endDateTime,
		int? maxParticipants,
		DateTimeOffset now,
		Guid? seriesId = null,
		string? recurrenceFrequency = null,
		int? recurrenceCount = null)
	{
		var validation = Validate(startDateTime, endDateTime, maxParticipants, now);
		if (validation.IsFailure)
			return Result.Failure<TimeSlot>(validation.Error);

		return new TimeSlot(
			TimeSlotId.New(),
			startDateTime,
			endDateTime,
			maxParticipants,
			seriesId,
			recurrenceFrequency,
			recurrenceCount);
	}

	public Result Update(DateTimeOffset startDateTime, DateTimeOffset endDateTime, int? maxParticipants, DateTimeOffset now)
	{
		var validation = Validate(startDateTime, endDateTime, maxParticipants, now);
		if (validation.IsFailure)
			return validation;

		StartDateTime = startDateTime;
		EndDateTime = endDateTime;
		MaxParticipants = maxParticipants;
		return Result.Success();
	}

	public Result UpdateCapacity(int? maxParticipants)
	{
		if (maxParticipants is <= 0)
			return Result.Failure(Error.Validation("TimeSlot.MaxParticipantsMustBePositive", "Max participants must be greater than zero."));

		MaxParticipants = maxParticipants;
		return Result.Success();
	}

	private static Result Validate(DateTimeOffset startDateTime, DateTimeOffset endDateTime, int? maxParticipants, DateTimeOffset now)
	{
		if (startDateTime <= now)
			return Result.Failure(Error.Validation("TimeSlot.StartMustBeFuture", "Start date must be in the future."));

		if (endDateTime <= startDateTime)
			return Result.Failure(Error.Validation("TimeSlot.EndMustBeAfterStart", "End date must be after start date."));

		if (maxParticipants is <= 0)
			return Result.Failure(Error.Validation("TimeSlot.MaxParticipantsMustBePositive", "Max participants must be greater than zero."));

		return Result.Success();
	}
}
