@startuml Fachliche Kontextsicht

!include <C4/C4_Context>
'LAYOUT_WITH_LEGEND()

title Fachliche Kontextsicht

Person(helferin, "Helferin Hannah", "Sucht nach Möglichkeiten regional ehrenamtilich tätig zu werden")

Person(organisator, "Organisator Olaf", "Erstellt Bedürfnisse für sein derzeitiges Event / sucht nach ehrentamtlicher Untersützung")

System(einsatzbereit, "Einsatzbereit", "Ermöglicht das Verwalten von regionalen Bedürfnissen und dem Anmelden helfen zu wollen")

Rel(helferin, einsatzbereit, "Suchanfrage und Anmeldung zu helfen")
Rel(organisator, einsatzbereit, "Pflegt die Bedürfnisse einer Organisation")

@enduml
