// Generated by scripts/generate-design-tokens.js - DO NOT EDIT.
//
// The source is the @theme block in src/styles/global.css. Change a value
// there and run `pnpm tokens:generate`; `pnpm check:design-tokens` fails CI
// when this file and that block disagree.

export const designTokens = {
	"--font-sans":
		'"Source Sans 3 Variable", ui-sans-serif, system-ui, sans-serif',
	"--font-display": '"Barlow Condensed", ui-sans-serif, system-ui, sans-serif',
	"--color-brand-50": "#f0faf5",
	"--color-brand-100": "#d6f0e3",
	"--color-brand-200": "#a8dfc3",
	"--color-brand-300": "#80cba6",
	"--color-brand-400": "#5bbf8c",
	"--color-brand-500": "#3eaf78",
	"--color-brand-600": "#2d8a5e",
	"--color-brand-700": "#226947",
	"--color-brand-800": "#1a3c2b",
	"--color-brand-900": "#0e251a",
	"--color-accent-400": "#f0b23a",
	"--radius-card": "1rem",
	"--container-page": "90rem",
	"--shadow-resting":
		"0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.06)",
	"--shadow-raised":
		"0 8px 20px -4px rgb(0 0 0 / 0.15), 0 4px 8px -4px rgb(0 0 0 / 0.1)",
	"--shadow-modal":
		"0 24px 48px -12px rgb(0 0 0 / 0.28), 0 8px 16px -8px rgb(0 0 0 / 0.16)",
} as const;

export type DesignTokenName = keyof typeof designTokens;

/** The raw value of a token, by its CSS custom-property name. */
export function designToken(name: DesignTokenName): string {
	return designTokens[name];
}
